Repository proofzero/rollupid, pull requests merged in 2022-08, with the labels that each got.

#647 CHORE(3iD): Update readme docs
  3iD/README.md
Labels: documentation

#655 CHORE(3iD-testing): Allow multi-wallet
  3iD/.env.example
  3iD/tests/e2e/specs/gate-allowed-spec.js
  3iD/tests/e2e/specs/gate-denied-spec.js
Labels: enhancement

#657 FIX(3iD-test): Fix GHA
  .github/workflows/next.yaml
Labels: bug

#642 FEAT(gate): Add Invitation Screen to Early Access Gate
  3iD/package-lock.json
  3iD/package.json
  3iD/src/App.tsx
  3iD/src/assets/card.png
  3iD/src/provider/kubelt.ts
  3iD/src/screens/funnel/Auth.tsx
  3iD/src/screens/funnel/Invite.tsx
  3iD/src/screens/profile/Details.tsx
  3iD/src/screens/profile/Settings.tsx
  3iD/src/types/Invitation.d.ts
Labels: enhancement

#658 CHORE(3iD): Formatting
  3iD/README.md
  3iD/src/App.tsx
  3iD/tests/e2e/.eslintrc.js
  3iD/tests/e2e/synpress.json
  3iD/tests/e2e/tsconfig.json
  3iD/tests/support/commands.js
  3iD/tests/support/index.js
Labels: enhancement

#659 CHORE(3iD): Update deps
  3iD/package-lock.json
  3iD/package.json
Labels: enhancement

#660 CHORE(Mint): Setup Wizard - Mint NFT
  3iD/src/assets/bullet_off.png
  3iD/src/assets/bullet_on.png
  3iD/src/provider/kubelt.ts
  3iD/src/screens/Layout.tsx
  3iD/src/screens/minting/Mint.tsx
Labels: enhancement

#663 CHORE(Mint): Confirm Transaction
  3iD/src/provider/kubelt.ts
  3iD/src/provider/web3.ts
  3iD/src/screens/minting/Mint.tsx
Labels: enhancement

#665 CHORE(Mint): Error
  3iD/src/assets/error.png
  3iD/src/assets/info.png
  3iD/src/screens/minting/Mint.tsx
Labels: enhancement

#669 FEAT(profile): Implement Navigation Menu
  3iD/package-lock.json
  3iD/package.json
  3iD/src/App.tsx
  3iD/src/assets/cog.png
  3iD/src/assets/copy.png
  3iD/src/assets/logout.png
  3iD/src/assets/spacer_195.png
  3iD/src/components/NavMenu.tsx
  3iD/src/screens/AuthLayout.tsx
Labels: enhancement

#675 feat(eth): invitations
  eth/invite/.gitignore
  eth/invite/README.md
  eth/invite/assets/3ID_NFT_CARD_NO_BG.svg
  eth/invite/contracts/Invite.sol
  eth/invite/hardhat.config.ts
  eth/invite/package-lock.json
  eth/invite/package.json
  eth/invite/plugin/InviteRuntimeField.ts
  eth/invite/plugin/index.ts
  eth/invite/plugin/type-extensions.ts
  eth/invite/scripts/deploy.ts
  eth/invite/test/Lock.ts
  eth/invite/tsconfig.json
Labels: enhancement

#661 FEAT(Mint): Create Mint NFT Flow
  3iD/src/assets/arrow_right_white.png
  3iD/src/assets/bullet_off.png
  3iD/src/assets/bullet_on.png
  3iD/src/assets/error.png
  3iD/src/assets/info.png
  3iD/src/assets/loading.png
  3iD/src/assets/sad.png
  3iD/src/assets/success.png
  3iD/src/provider/kubelt.ts
  3iD/src/provider/web3.ts
  3iD/src/screens/AuthLayout.tsx
  3iD/src/screens/funnel/Auth.tsx
  3iD/src/screens/funnel/Gate.tsx
  3iD/src/screens/funnel/Invite.tsx
  3iD/src/screens/funnel/Landing.tsx
  3iD/src/screens/minting/Mint.tsx
  src/main/com/kubelt/lib/oort.cljs
  src/main/com/kubelt/sdk/v1/oort.cljs
  src/test/com/kubelt/rpc/auth_test.cljs
  src/test/com/kubelt/rpc/nfts_test.cljs
  src/test/com/kubelt/rpc/oort_test.cljs
  src/test/com/kubelt/rpc/profile_test.cljs
  src/test/com/kubelt/rpc/sdk_test.cljs
Labels: enhancement

#680 FIX(3iD): Update tests
  3iD/tests/e2e/specs/gate-allowed-spec.js
  3iD/tests/e2e/specs/gate-denied-spec.js
Labels: enhancement

#681 FIX(3iD): Undefined funnel state
  3iD/src/provider/kubelt.ts
Labels: enhancement

#668 FEAT(ens): Implement Set Profile URL Flow
  3iD/src/App.tsx
  3iD/src/assets/Bullet.png
  3iD/src/assets/combo_false.png
  3iD/src/assets/combo_true.png
  3iD/src/components/NavMenu.tsx
  3iD/src/provider/kubelt.ts
  3iD/src/screens/funnel/Auth.tsx
  3iD/src/screens/funnel/Gate.tsx
  3iD/src/screens/funnel/Invite.tsx
  3iD/src/screens/funnel/Landing.tsx
  3iD/src/screens/minting/Mint.tsx
  3iD/src/screens/profile/Details.tsx
  3iD/src/screens/profile/Naming.tsx
  3iD/src/screens/profile/Settings.tsx
Labels: enhancement

#682 FIX(3iD): Asset casing
  3iD/src/assets/bullet.png
Labels: enhancement

#683 fix(lint): Fix `yamllint` Errors
  .github/workflows/release.yaml
  nftar/cloudbuild.yaml
Labels: bug

#687 CHORE(Onboarding): Create onboarding screen
  3iD/src/App.tsx
  3iD/src/screens/minting/Mint.tsx
  3iD/src/screens/onboarding/Onboard.tsx
Labels: enhancement

#691 CHORE(onboarding): Hero unit
  3iD/src/assets/discord.png
  3iD/src/assets/twitter.png
  3iD/src/screens/onboarding/Onboard.tsx
Labels: enhancement

#692 CHORE(onboarding): Mint banner
  3iD/src/screens/onboarding/Onboard.tsx
Labels: enhancement

#693 FEAT(onboarding): Implement Onboarding Screen
  3iD/src/App.tsx
  3iD/src/assets/discord.png
  3iD/src/assets/dropdown.png
  3iD/src/assets/step_complete.png
  3iD/src/assets/step_soon.png
  3iD/src/assets/twitter.png
  3iD/src/screens/AuthLayout.tsx
  3iD/src/screens/minting/Mint.tsx
  3iD/src/screens/onboarding/Onboard.tsx
Labels: enhancement

#699 FEAT(3id): Replace kb_getProfile and kb_setProfile methods
  3iD/src/provider/kubelt.ts
Labels: enhancement

#700 FIX(3iD): Various fixes
  3iD/.env.example
  3iD/src/provider/kubelt.ts
  3iD/src/screens/funnel/Auth.tsx
  3iD/src/screens/funnel/Invite.tsx
  3iD/src/screens/funnel/Landing.tsx
  3iD/src/screens/profile/Details.tsx
  3iD/src/screens/profile/Settings.tsx
Labels: bug, enhancement

#697 chore(github): Updates to issues, PR templates, and settings.
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/chore.md
  .github/ISSUE_TEMPLATE/feature.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/settings.yml
Labels: enhancement

#702 fix(settings): Update settings.yaml to agree with Pulumi.
  .github/settings.yml
Labels: bug

#705 fix(nftar): minor improvements for `genPFP` method
  nftar/src/app.js
Labels: bug

#706 CHORE(3iD): Adapt mint call
  3iD/src/provider/kubelt.ts
  3iD/src/screens/minting/Mint.tsx
Labels: enhancement

#708 FIX(3iD): Load IPFS from gateway
  3iD/src/provider/kubelt.ts
  3iD/src/screens/funnel/Invite.tsx
  3iD/src/screens/minting/Mint.tsx
Labels: enhancement

#703 feat(invite): Housekeeping updates to invitation smart contract repo.
  eth/invite/LICENSE.md
  eth/invite/hardhat.config.ts
  eth/invite/package-lock.json
  eth/invite/package.json
  eth/invite/scripts/deploy.ts
Labels: enhancement

#711 docs(README): Added brief intro and deployment workflow instructions.
  eth/invite/README.md
  eth/invite/hardhat.config.ts
Labels: documentation

#709 FIX(3iD): Update FAQ copy
  3iD/src/screens/funnel/Invite.tsx
  3iD/src/screens/onboarding/Onboard.tsx
Labels: enhancement

#718 FEAT(3iD): Service extraction
  3iD/src/hooks/sdkAuth.ts
  3iD/src/provider/kubelt.ts
  3iD/src/provider/web3.ts
  3iD/src/screens/AuthLayout.tsx
  3iD/src/screens/funnel/Auth.tsx
  3iD/src/screens/funnel/Invite.tsx
  3iD/src/screens/funnel/Landing.tsx
  3iD/src/screens/minting/Mint.tsx
  3iD/src/screens/onboarding/Onboard.tsx
  3iD/src/screens/profile/Details.tsx
  3iD/src/screens/profile/Naming.tsx
  3iD/src/screens/profile/Settings.tsx
  3iD/src/services/storage/index.ts
  3iD/src/services/threeid/funnel.ts
  3iD/src/services/threeid/index.ts
  3iD/src/services/threeid/inviting.ts
  3iD/src/services/threeid/minting.ts
  3iD/src/services/threeid/naming.ts
  3iD/src/services/threeid/profile.ts
  3iD/src/services/threeid/types.d.ts
  3iD/src/types/Invitation.d.ts
  3iD/src/types/Profile.d.ts
Labels: enhancement

#719 docs(README): Added Typechain Regeneration Information
  eth/invite/README.md
Labels: documentation

#721 docs(README): Add cache busting instructions.
  3iD/README.md
Labels: documentation

#670 FEAT(Three-id): Extract Profile Details screen
  3iD/src/App.tsx
  3iD/src/assets/book.png
  3iD/src/assets/find.svg
  3iD/src/assets/mint_bg.png
  3iD/src/assets/mint_large.png
  3iD/src/assets/opensea.png
  3iD/src/assets/polygon.png
  3iD/src/assets/rarible.png
  3iD/src/assets/superrare.png
  3iD/src/components/NavMenu.tsx
  3iD/src/hooks/profile.ts
  3iD/src/screens/AppLayout.tsx
  3iD/src/screens/AuthLayout.tsx
  3iD/src/screens/profile/Details.tsx
  3iD/src/screens/profile/Settings.tsx
Labels: enhancement

#738 feat(invite): Add Rinkeby, Destructor
  eth/invite/contracts/Invite.sol
  eth/invite/hardhat.config.ts
  eth/invite/scripts/deploy.ts
Labels: enhancement

#740 chore(gpg): Add alfl commit signing public key.
  gpg/alfl.asc
Labels: security

#741 FEAT(invite): Add Rinkeby and Destructor
  eth/invite/README.md
  eth/invite/hardhat.config.ts
Labels: enhancement

#743 FEAT(3iD): State management
  3iD/package-lock.json
  3iD/package.json
  3iD/src/App.tsx
  3iD/src/components/NavMenu.tsx
  3iD/src/hooks/profile.ts
  3iD/src/hooks/state.ts
  3iD/src/provider/web3.ts
  3iD/src/screens/AppLayout.tsx
  3iD/src/screens/AuthLayout.tsx
  3iD/src/screens/profile/Details.tsx
  3iD/src/screens/profile/Settings.tsx
  3iD/src/state/slices/profile.ts
  3iD/src/state/store.ts
Labels: enhancement

#744 FIX(3iD): Try restore SDK
  3iD/src/provider/kubelt.ts
Labels: bug

#746 feat(eth): convert invite deploy to task
  eth/.gitignore
  eth/invite/.gitignore
  eth/invite/hardhat.config.ts
  eth/invite/package-lock.json
  eth/invite/package.json
  eth/invite/scripts/.gitkeep
  eth/invite/scripts/deploy.ts
Labels: enhancement

#748 FEAT(3iD): Handle chain changed event
  3iD/src/provider/kubelt.ts
  3iD/src/provider/web3.ts
Labels: enhancement

#751 feat(invite): Add Polygon.
  eth/invite/hardhat.config.ts
Labels: enhancement

#759 FEAT(3iD): Use Metamask's detect Ethereum provider
  3iD/package-lock.json
  3iD/package.json
  3iD/src/provider/web3.ts
Labels: enhancement
