Repository proofzero/rollupid, pull requests merged in 2022-04, with the labels that each got.

#241 KUBELT > CHORE (Sanity): Fix unmet dependency
  package-lock.json
  package.json
Labels: bug

#248 CHORE(www): Clean up index into partials
  www/config/_default/params.toml
  www/layouts/index.html
  www/layouts/partials/body/script.html
  www/layouts/partials/head/head.html
  www/layouts/partials/head/seo.html
  www/layouts/partials/head/stylesheet.html
  www/layouts/partials/homepage/cta.html
  www/layouts/partials/homepage/features.html
  www/layouts/partials/homepage/footer.html
  www/layouts/partials/homepage/hero-script.html
  www/layouts/partials/homepage/hero.html
  www/layouts/partials/homepage/logocloud.html
  www/layouts/partials/homepage/navbar.html
  www/layouts/partials/homepage/users.html
Labels: enhancement

#249 chore(www): Clean up index into partials
  www/layouts/index.html
  www/layouts/partials/head/head.html
  www/layouts/partials/head/stylesheet.html
  www/layouts/partials/homepage/body/script.html
  www/layouts/partials/homepage/head/head.html
  www/layouts/partials/homepage/head/stylesheet.html
Labels: enhancement

#266 CHORE(Sanity): Remove kItem definition dependency
  bb.edn
  packages/sanity-plugin-kubelt/src/actions/KubeltPublishAction.tsx
  packages/sanity-plugin-kubelt/src/badges/KubeltNamedBadge.tsx
  packages/sanity-plugin-kubelt/src/resolvers/badgeResolver.ts
  packages/sanity-plugin-kubelt/src/services/semanticService.test.ts
Labels: enhancement

#290 FEAT(Sanity): Add checksum to client account computation
  packages/sanity-plugin-kubelt/src/domain/kubeltWallet.ts
Labels: enhancement

#294 chore(dapp): Add Cypress for testing frontend locally & on CI
  .github/workflows/develop.yaml
  bb.edn
  dapp/cypress.json
  dapp/cypress/integration/routes.spec.js
  dapp/cypress/plugins/index.js
  dapp/cypress/support/commands.js
  dapp/cypress/support/index.js
  dapp/package-lock.json
  dapp/package.json
  dapp/src/dapp/components/button.cljs
  dapp/src/dapp/components/sidebar.cljs
  dapp/src/dapp/pages/dashboard.cljs
  package.json
Labels: enhancement

#286 docs(blog): Add First Post and CRT Case Study
  www/config/_default/config.toml
  www/config/_default/menus/menus.en.toml
  www/config/_default/params.toml
  www/content/en/blog/accelerating-courtyard.md
  www/content/en/blog/moxie-vitalik-kubelt.md
  www/content/en/contributors/alfl.md
  www/content/en/docs/basics/how-it-works.md
  www/content/en/showcase/showcase.md
Labels: documentation

#292 feat(dapp) use timbre for logging
  dapp/src/dapp/components/login.cljs
  dapp/src/dapp/pages/dashboard.cljs
  dapp/src/dapp/routes.cljs
  dapp/src/dapp/utils.cljs
  dapp/src/dapp/wallet.cljs
Labels: enhancement

#305 feat(dapp): Update web3modal style to match mocks + refactor into own component ns
  dapp/src/dapp/components/web3_modal.cljs
  dapp/src/dapp/pages/dashboard.cljs
  dapp/src/dapp/wallet.cljs
Labels: enhancement

#311 feat(dapp): Implement wallet disconnect
  dapp/src/dapp/components/header.cljs
  dapp/src/dapp/components/web3_modal.cljs
  dapp/src/dapp/pages/dashboard.cljs
  dapp/src/dapp/wallet.cljs
Labels: enhancement

#326 chore(dapp): Re-frame tests w/karma for local + CI testing
  .github/workflows/develop.yaml
  bb.edn
  dapp/.gitignore
  dapp/test/dapp/integration/auth_test.cljs
  package-lock.json
  package.json
  shadow-cljs.edn
  src/test/car/block_test.cljs
  src/test/car/build_test.cljc
Labels: enhancement

#343 chore(dapp): Add auth test for wallet authenticate/disconnect via dapp
  .github/workflows/develop.yaml
  dapp/src/dapp/core.cljs
  dapp/src/dapp/wallet.cljs
  dapp/test/dapp/integration/auth_test.cljs
  shadow-cljs.edn
  src/main/com/kubelt/lib/http/browser.cljs
  src/main/com/kubelt/lib/wallet/node.cljs
  src/main/com/kubelt/lib/wallet/shared.cljc
Labels: enhancement

#365 chore(dapp/integration-tests): Update how JWT is retrieved from response body to fix tests + correct build badge
  README.md
  src/main/com/kubelt/sdk/v1/core.cljs
Labels: bug
