Repository proofzero/rollupid, pull requests merged in 2022-12, with the labels that each got.

#1117 bug(system): address env check
  platform/address/src/jsonrpc.ts
Labels: bug, enhancement

#1127 bug(threeid): css regressions
  apps/threeid/app/components/FAQ/index.tsx
  apps/threeid/app/components/inputs/InputText.tsx
  apps/threeid/app/components/inputs/InputTextarea.tsx
  apps/threeid/app/components/nft-collection/ProfileNftCollection.tsx
  apps/threeid/app/components/typography/Heading.tsx
  apps/threeid/app/components/typography/SmallRegularBlock.tsx
  apps/threeid/app/routes/$profile.tsx
  apps/threeid/app/routes/account/dashboard.tsx
  apps/threeid/app/routes/account/settings/profile.tsx
  packages/design-system/src/atoms/buttons/ButtonAnchor.tsx
  packages/design-system/src/atoms/text/Text.tsx
Labels: bug

#1129 bug(threeid): profile ownership
  apps/passport/app/routes/authenticate/$address.token.tsx
  apps/passport/package.json
  apps/threeid/app/routes/$profile.tsx
  platform/commons/src/urns.ts
Labels: bug

#1139 fix(threeid): varifixes
  apps/threeid/app/components/nft-collection/ProfileNftCollection.tsx
  apps/threeid/app/routes/$profile.tsx
  apps/threeid/app/routes/account/dashboard.tsx
  apps/threeid/app/routes/account/settings/profile.tsx
  apps/threeid/app/routes/nfts/index.tsx
  apps/threeid/gql/nfts.graphql
  platform/galaxy/src/schema/resolvers/nfts.ts
  platform/galaxy/src/schema/types/nfts.ts
Labels: bug, enhancement

#1143 fix(passport): ui regressions
  apps/passport/tailwind.config.js
Labels: bug

#1144 fix(threeid): computed tailwind classes
  apps/threeid/app/components/inputs/InputText.tsx
  apps/threeid/app/components/inputs/InputTextarea.tsx
Labels: bug

#1145 feat(polygon): tighten nft calls
  packages/alchemy-client/index.ts
  platform/galaxy/.dev.vars.example
  platform/galaxy/src/env.ts
  platform/galaxy/src/schema/resolvers/nfts.ts
Labels: enhancement

#1153 fix(storybook): global import
  apps/passport/.storybook/preview.js
Labels: bug

#1177 bug(threeid): gallery cache
  apps/threeid/app/components/nft-collection/ProfileNftCollection.tsx
Labels: bug

#1178 bug(threeid): profile ens auth match
  apps/threeid/app/routes/$profile.json.tsx
  apps/threeid/app/routes/$profile.tsx
  apps/threeid/gql/ens.graphql
  platform/galaxy/src/schema/resolvers/address.ts
  platform/galaxy/src/schema/resolvers/clients/ens-utils.ts
  platform/galaxy/src/schema/types/address.ts
Labels: bug, enhancement

#1175 feat(openrpc): add support for scheduled alarms on components
  packages/openrpc/component/alarm.ts
  packages/openrpc/component/index.ts
  packages/openrpc/middleware/datadog.ts
  packages/openrpc/middleware/oort.ts
  packages/openrpc/package.json
  platform/ping/curl/kb_delayInit.json
  platform/ping/curl/kb_init.json
  platform/ping/curl/kb_ping.json
  platform/ping/curl/kb_pong.json
  platform/ping/package.json
  platform/ping/src/core.ts
  platform/ping/src/index.ts
  platform/ping/src/node/reply/index.ts
  platform/ping/src/node/reply/schema.ts
  platform/ping/src/openrpc.json
  platform/ping/src/schema.ts
  platform/ping/src/types.ts
  platform/ping/wrangler.toml
  platform/starbase/src/index.ts
  platform/starbase/src/nodes/application/index.ts
  yarn.lock
Labels: enhancement

#1184 feat(sb): more edges integration, flesh out API methods
  packages/openrpc/component/alarm.ts
  packages/openrpc/component/index.ts
  packages/openrpc/impl/client.ts
  packages/openrpc/impl/context.ts
  packages/openrpc/impl/index.ts
  packages/openrpc/impl/utility.ts
  packages/urns/application.ts
  platform/edges/src/index.ts
  platform/starbase/curl/kb_appCreate.json
  platform/starbase/curl/kb_appList.json
  platform/starbase/curl/kb_appRotateSecret.json
  platform/starbase/package.json
  platform/starbase/src/edge.ts
  platform/starbase/src/index.ts
  platform/starbase/src/nodes/application/index.ts
  platform/starbase/src/nodes/application/schema.ts
  platform/starbase/src/schema.ts
  platform/starbase/src/token.ts
  yarn.lock
Labels: enhancement

#1195 fix(address): parameter destructuring
  platform/address/src/jsonrpc/methods/getNonce.ts
Labels: bug

#1202 fix(passport): address node type
  apps/passport/app/routes/authenticate/$address.sign.tsx
Labels: bug

#1205 bug(passport): error screen positioning
  apps/passport/app/root.tsx
Labels: bug, enhancement, good-first-issue

#1188 docs(3id): Docs Skeleton
  docs/3id/faq/index.md
  docs/3id/guides/3id-auth.md
  docs/3id/guides/3id-public-profiles.md
  docs/3id/guides/index.md
  docs/3id/overview/index.md
  docs/3id/quickstart/index.md
  docs/3id/reference/index.md
  docs/CONTENTS.md
Labels: documentation

#1228 docs(3id): Migrate Docs from Notion
  docs/3id/quickstart/img/console-app-0xauth.png
  docs/3id/quickstart/img/console-app-create.png
  docs/3id/quickstart/img/console-app-details.png
  docs/3id/quickstart/img/console-dashboard.png
  docs/3id/quickstart/img/passport.png
  docs/3id/quickstart/index.md
Labels: documentation

#1225 fix(nftar): Fix crash in error handler.
  projects/nftar/src/app.js
  projects/nftar/src/utils.js
Labels: enhancement

#1257 docs(3id): Overview Iteration and Content Structure Refactoring
  .github/settings.yml
  docs/3id/console/index.md
  docs/3id/faq/index.md
  docs/3id/galaxy/index.md
  docs/3id/guides/app-setup.md
  docs/3id/overview/index.md
  docs/3id/passport/index.md
  docs/3id/profile/index.md
  docs/3id/quickstart/index.md
  docs/3id/reference/console.md
  docs/3id/reference/index.md
  docs/3id/reference/passport.md
  docs/3id/reference/profile.md
  docs/CONTENTS.md
  docs/index.md
Labels: documentation

#1259 fix(address): nonce challenge time-to-live
  platform/address/src/nodes/crypto.ts
  platform/address/src/types.ts
Labels: bug

#1260 fix(access): authorization code time-to-live
  platform/access/src/constants.ts
  platform/access/src/nodes/authorization.ts
  platform/access/src/types.ts
Labels: bug

#1254 feat(edges): update shape of returned edges, include more data
  packages/graph/impl/index.ts
  packages/graph/index.ts
  packages/graph/types.ts
  platform/edges/curl/kb_makeEdge.json
  platform/edges/src/db/impl/index.ts
  platform/edges/src/db/impl/insert.ts
  platform/edges/src/db/impl/remove.ts
  platform/edges/src/db/impl/select.ts
  platform/edges/src/db/index.ts
  platform/edges/src/db/types.ts
  platform/edges/src/error.ts
  platform/edges/src/index.ts
  platform/edges/test/db/basic.ts
  platform/starbase/src/index.ts
Labels: enhancement

#1270 docs(3id): Overview Iterations
  CONTRIBUTING.md
  docs/3id/console/index.md
  docs/3id/console/reference.md
  docs/3id/galaxy/index.md
  docs/3id/galaxy/reference.md
  docs/3id/guides/app-setup.md
  docs/3id/guides/index.md
  docs/3id/img/console-app-0xauth.png
  docs/3id/overview/glossary.md
  docs/3id/overview/index.md
  docs/3id/passport/index.md
  docs/3id/passport/reference.md
  docs/3id/profile/index.md
  docs/3id/profile/reference.md
  docs/CONTENTS.md
  docs/README.md
Labels: documentation

#1262 doc(openrpc): add docs for the @kubelt/openrpc package
  packages/openrpc/component/README.md
  packages/openrpc/component/index.ts
Labels: documentation

#1288 bug(console): uifix
  .yarn/cache/esbuild-windows-64-npm-0.15.18-f926268f42-8.zip
  apps/console/app/components/Applications/ApplicationListItem.tsx
Labels: bug

#1275 feat(console): rotate secret
  apps/console/app/components/Applications/Dashboard/ApplicationDashboard.tsx
  apps/console/app/routes/apps/$appId/index.tsx
  apps/console/app/routes/apps/$clientId.tsx
  apps/console/app/routes/apps/$clientId/auth.tsx
  apps/console/app/routes/apps/$clientId/index.tsx
  packages/platform-clients/starbase.ts
  platform/starbase/src/index.ts
  platform/starbase/src/nodes/application/index.ts
  platform/starbase/src/nodes/application/schema.ts
  platform/starbase/src/schema.ts
  platform/starbase/src/types.ts
Labels: enhancement

#1290 feat(console): brand side menu
  apps/console/app/components/SiteMenu/appSelect.tsx
  apps/console/app/components/SiteMenu/index.tsx
  apps/console/app/images/3id_console_logo.svg
  apps/console/app/routes/dashboard/index.tsx
Labels: bug, enhancement

#1297 feat(console): align side menu to Figma
  apps/console/app/components/SiteMenu/appSelect.tsx
Labels: enhancement

#1325 chore(account): simplify `state` type declaration
  platform/account/src/nodes/account.ts
  platform/account/src/types.ts
Labels: bug
