Repository proofzero/rollupid, pull requests merged in 2022-06, with the labels that each got.

#448 chore(dapp): Migrate to cypress 10.0.0 & update test configuration to match
  dapp/cypress.config.js
  dapp/cypress.json
  dapp/cypress/e2e/routes.cy.js
  dapp/cypress/support/e2e.js
  dapp/package-lock.json
  dapp/package.json
Labels: bug

#480 chore(gha): update build pipelines and tooling
  .github/workflows/develop.yaml
  .github/workflows/next.yaml
  .github/workflows/ref-docs.yaml
  .github/workflows/release.yaml
  deps.edn
Labels: dependencies

#490 FEAT(three-id): bootstrap expo solution
  package-lock.json
  package.json
  packages/three-id/.gitignore
  packages/three-id/App.tsx
  packages/three-id/app.json
  packages/three-id/assets/adaptive-icon.png
  packages/three-id/assets/favicon.png
  packages/three-id/assets/icon.png
  packages/three-id/assets/splash.png
  packages/three-id/assets/three-id-logo.svg
  packages/three-id/babel.config.js
  packages/three-id/hooks/account.ts
  packages/three-id/package-lock.json
  packages/three-id/package.json
  packages/three-id/provider/kubelt.ts
  packages/three-id/provider/web3.ts
  packages/three-id/screens/Auth.tsx
  packages/three-id/screens/Gate.tsx
  packages/three-id/screens/Landing.tsx
  packages/three-id/screens/Layout.tsx
  packages/three-id/tsconfig.json
Labels: enhancement

#500 FIX(three-id): Update Expo manifest
  three-id/app.json
  three-id/src/index.ts
Labels: bug

#501 FEAT(claim): Add whitelist check
  src/main/com/kubelt/lib/rpc.cljs
  src/main/com/kubelt/sdk.cljs
  src/main/com/kubelt/sdk/v1/oort.cljs
  three-id/src/provider/kubelt.ts
  three-id/src/screens/Auth.tsx
Labels: enhancement

#502 FEAT(claim): Add env variables for urls
  three-id/.env.example
  three-id/app.config.ts
  three-id/app.json
  three-id/package-lock.json
  three-id/package.json
  three-id/src/provider/kubelt.ts
  three-id/src/screens/Auth.tsx
  three-id/src/screens/Gate.tsx
Labels: enhancement
