Repository proofzero/rollupid, pull requests merged in 2022-11, with the labels that each got.

#908 FEAT(3iD): Expand providers
  .github/workflows/main-threeid.yaml
  .github/workflows/next-threeid.yaml
  .github/workflows/release-threeid.yaml
  apps/threeid/.dev.vars.example
  apps/threeid/app/routes/$profile.json.tsx
  apps/threeid/app/routes/$profile.tsx
  apps/threeid/app/routes/auth.tsx
  apps/threeid/app/routes/onboard.tsx
  apps/threeid/app/routes/onboard/mint/index.tsx
Labels: bug, enhancement

#902 chore(icons): set up GHA workflows
  .github/workflows/main-icons.yaml
  .github/workflows/next-icons.yaml
  .github/workflows/release-icons.yaml
  .gitignore
  README.md
  platform/icons/.dev.vars.example
  platform/icons/src/index.ts
  platform/icons/wrangler.toml
Labels: enhancement

#912 feat(sb): various storage-related updates and fixes
  platform/starbase/component/application/index.ts
  platform/starbase/component/application/package-lock.json
  platform/starbase/component/application/package.json
  platform/starbase/component/contract/index.ts
  platform/starbase/component/contract/package-lock.json
  platform/starbase/component/contract/package.json
  platform/starbase/component/package.json
  platform/starbase/component/user/index.ts
  platform/starbase/component/user/package-lock.json
  platform/starbase/component/user/package.json
  platform/starbase/lib/openrpc/component/index.ts
  platform/starbase/lib/openrpc/impl/jsonrpc.ts
  platform/starbase/lib/openrpc/impl/scopes.ts
  platform/starbase/lib/openrpc/index.ts
  platform/starbase/lib/openrpc/package-lock.json
  platform/starbase/lib/openrpc/package.json
  platform/starbase/lib/package.json
  platform/starbase/package.json
  platform/starbase/worker/package-lock.json
  platform/starbase/worker/package.json
  platform/starbase/worker/src/index.ts
  yarn.lock
Labels: enhancement

#920 feat(nftar): Add OG:Image Generator
  projects/nftar/index.js
  projects/nftar/package.json
  projects/nftar/src/app.js
Labels: enhancement

#922 FIX(3iD): Client Side Image Upload
  apps/threeid/app/routes/$profile.tsx
  apps/threeid/app/routes/account/settings/profile.tsx
  apps/threeid/app/routes/api/image-upload-url.tsx
  apps/threeid/app/routes/api/update-cover.tsx
  apps/threeid/app/routes/api/upload-cover.tsx
  apps/threeid/app/routes/api/upload-image.tsx
Labels: bug, enhancement

#923 feat(oort): delete index record of non-existing object
  platform/oort/src/packages/objects/objects.ts
Labels: bug

#924 chore: update yarn.lock
  yarn.lock
Labels: dependencies

#927 feat(threeid): Add OG Image
  apps/threeid/app/helpers/validate-proof.ts
  apps/threeid/app/routes/$profile.tsx
  platform/icons/package.json
  platform/icons/wrangler.toml
  yarn.lock
Labels: enhancement

#930 FIX(3iD-Deploy): Alchemy env vars
  .github/workflows/main-threeid.yaml
  .github/workflows/next-threeid.yaml
  .github/workflows/release-threeid.yaml
  apps/threeid/app/routes/nfts/index.tsx
Labels: bug

#933 feat(nftar): Remove 409 Check, Bugfixes and Error Checking
  projects/nftar/src/app.js
  projects/nftar/src/traits.js
  projects/nftar/tests/utils.test.js
Labels: enhancement

#929 feat(threeid): Add More OG:Tags
  apps/threeid/app/routes/$profile.tsx
Labels: enhancement

#931 FEAT(3iD): Profile spacing
  apps/threeid/app/routes/$profile.tsx
Labels: bug

#937 feat(threeid): Twitter Meta Tags
  apps/threeid/app/routes/$profile.tsx
Labels: enhancement

#941 fix(workspaces): find only packages in sub-workspaces
  package.json
Labels: bug

#943 chore(workspace): update `yarn.lock` file
  yarn.lock
Labels: dependencies

#944 chore(workspaces): treat sub-workspaces as a separate project
  package.json
Labels: dependencies

#942 fix(threeid): remove deprecated claim requirement
  platform/oort/src/packages/ens/ens.ts
  platform/oort/src/packages/threeid/threeid.ts
Labels: bug

#958 chore(oort): move ESLint configuration
  platform/oort/.eslintrc.json
Labels: bug

#959 fix(crdt): add missing dependency
  smartcontracts/eth/crdt/package.json
  yarn.lock
Labels: dependencies

#976 bug(threeid): tailwind paths
  apps/threeid/tailwind.config.js
Labels: bug

#978 bug(threeid): ens profile ownership check
  apps/threeid/app/routes/$profile.tsx
Labels: bug

#979 bug(threeid): nft load fail placeholder
  apps/threeid/app/assets/missing-nft.svg
  apps/threeid/app/components/nft-collection/ModaledNft.tsx
  apps/threeid/app/components/nft-collection/SelectableNft.tsx
Labels: bug, enhancement

#980 fix(threeid): bio linebreak
  apps/threeid/app/routes/$profile.tsx
Labels: bug, enhancement

#981 feat(threeid): profile website regex
  apps/threeid/app/routes/account/settings/profile.tsx
Labels: bug, enhancement

#982 fix(3id): nft page size and opensea schema
  apps/threeid/app/routes/nfts/index.tsx
Labels: bug, enhancement

#983 feat(3id): nft collection filtering
  apps/threeid/app/utils/alchemy.server.tsx
Labels: enhancement

#984 Removed NFT property title assumption & added openSea object
  apps/threeid/app/components/nft-collection/NftModal.tsx
  apps/threeid/app/routes/nfts/index.tsx
  apps/threeid/app/utils/alchemy.server.tsx
Labels: bug, enhancement

#986 feat(3id): hide error'd nfts and use thumbnails
  apps/threeid/app/components/nft-collection/ModaledNft.tsx
  apps/threeid/app/routes/nfts/index.tsx
  apps/threeid/app/utils/alchemy.server.tsx
Labels: bug, enhancement

#987 fix(3id): profile filtering
  apps/threeid/app/components/nft-collection/NftModal.tsx
  apps/threeid/app/routes/nfts/index.tsx
Labels: bug

#969 feat(sb): use client to invoke remote methods
  apps/console/app/shared/utilities/icon.server.tsx
  platform/starbase/component/application/index.ts
  platform/starbase/component/application/schema.ts
  platform/starbase/component/contract/schema.ts
  platform/starbase/component/user/schema.ts
  platform/starbase/lib/openrpc/component/index.ts
  platform/starbase/lib/openrpc/impl/client.ts
  platform/starbase/lib/openrpc/impl/context.ts
  platform/starbase/lib/openrpc/impl/index.ts
  platform/starbase/lib/openrpc/impl/router.ts
  platform/starbase/lib/openrpc/index.ts
  platform/starbase/lib/openrpc/middleware/analytics.ts
  platform/starbase/lib/openrpc/middleware/authenticate.ts
  platform/starbase/lib/openrpc/middleware/datadog.ts
  platform/starbase/lib/openrpc/middleware/geolocation.ts
  platform/starbase/lib/openrpc/middleware/local.ts
  platform/starbase/lib/openrpc/middleware/oort.ts
  platform/starbase/lib/openrpc/package.json
  platform/starbase/worker/curl/kb_appAuthInfo.json
  platform/starbase/worker/curl/kb_appFetch.json
  platform/starbase/worker/curl/kb_appStore.json
  platform/starbase/worker/src/index.ts
  platform/starbase/worker/src/middleware.ts
  platform/starbase/worker/src/schema.ts
  platform/starbase/worker/src/secret.ts
  platform/starbase/worker/wrangler.toml
  platform/yarn.lock
Labels: enhancement

#904 feat(workers): introduce `@kubelt/worker-commons` package
  platform/worker-commons/.eslintrc.json
  platform/worker-commons/.prettierrc
  platform/worker-commons/package.json
  platform/worker-commons/src/constants.ts
  platform/worker-commons/src/durable_object.ts
  platform/worker-commons/src/index.ts
  platform/worker-commons/src/jsonrpc.ts
  platform/worker-commons/src/routers/core.ts
  platform/worker-commons/src/routers/cors.ts
  platform/worker-commons/src/routers/errors.ts
  platform/worker-commons/src/routers/index.ts
  platform/worker-commons/src/routers/openrpc.ts
  platform/worker-commons/src/utils/getCoreId.ts
  platform/worker-commons/src/utils/index.ts
  platform/worker-commons/tsconfig.json
  platform/yarn.lock
Labels: enhancement

#988 feat(threeid): Update og:tags
  apps/threeid/app/routes/$profile.tsx
Labels: enhancement

#990 fix(threeid): ux wins
  apps/threeid/app/components/head-nav/index.tsx
  apps/threeid/app/components/inputs/InputText.tsx
  apps/threeid/app/components/nft-collection/ModaledNft.tsx
  apps/threeid/app/components/sign-out-link/index.tsx
  apps/threeid/app/routes/account.tsx
  apps/threeid/app/routes/account/settings.tsx
  apps/threeid/app/routes/account/settings/profile.tsx
  apps/threeid/app/styles/auth.scss
Labels: bug, enhancement

#1000 chore(workspaces): use root/node_modules for dependencies
  .github/workflows/main-console.yaml
  .github/workflows/main-galaxy.yaml
  .github/workflows/main-icons.yaml
  .github/workflows/main-nftar.yaml
  .github/workflows/main-oort.yaml
  .github/workflows/main-passport.yaml
  .github/workflows/main-redeem.yaml
  .github/workflows/main-smartcontracts.yaml
  .github/workflows/main-threeid.yaml
  .github/workflows/next-console.yaml
  .github/workflows/next-galaxy.yaml
  .github/workflows/next-icons.yaml
  .github/workflows/next-oort.yaml
  .github/workflows/next-passport.yaml
  .github/workflows/next-redeem.yaml
  .github/workflows/next-threeid.yaml
  .github/workflows/pr-apps.yaml
  .github/workflows/pr-packages.yaml
  .github/workflows/pr-platform.yaml
  .github/workflows/pr-projects.yaml
  .github/workflows/pr-smartcontracts.yaml
  .github/workflows/release-console.yaml
  .github/workflows/release-galaxy.yaml
  .github/workflows/release-icons.yaml
  .github/workflows/release-oort.yaml
  .github/workflows/release-passport.yaml
  .github/workflows/release-redeem.yaml
  .github/workflows/release-threeid.yaml
  apps/yarn.lock
  packages/yarn.lock
  platform/yarn.lock
  projects/yarn.lock
  smartcontracts/yarn.lock
  www/yarn.lock
  yarn.lock
Labels: dependencies

#1003 feat(threeid): rework profile
  apps/threeid/app/components/buttons/Button.scss
  apps/threeid/app/components/buttons/index.ts
  apps/threeid/app/components/spinner/index.tsx
  apps/threeid/app/helpers/gateway-from-ipfs.ts
  apps/threeid/app/routes/$profile.tsx
  apps/threeid/app/styles/base.scss
  apps/threeid/tailwind.config.js
Labels: enhancement

#1005 chore(sb): workflows
  .github/workflows/main-starbase.yaml
  .github/workflows/next-starbase.yaml
  .github/workflows/release-starbase.yaml
  apps/console/wrangler.toml
  platform/starbase/wrangler.toml
Labels: enhancement

#906 feat(passport): introduce `@kubelt/passport-worker` package
  platform/passport-worker/.eslintrc.json
  platform/passport-worker/.gitignore
  platform/passport-worker/.prettierrc.json
  platform/passport-worker/package.json
  platform/passport-worker/src/constants.ts
  platform/passport-worker/src/core.ts
  platform/passport-worker/src/index.ts
  platform/passport-worker/src/openrpc.json
  platform/passport-worker/src/types.ts
  platform/passport-worker/tsconfig.json
  platform/passport-worker/wrangler.toml
  platform/ping-worker/.eslintrc.json
  platform/ping-worker/.gitignore
  platform/ping-worker/.prettierrc.json
  platform/ping-worker/package.json
  platform/ping-worker/src/core.ts
  platform/ping-worker/src/index.ts
  platform/ping-worker/src/openrpc.json
  platform/ping-worker/src/types.ts
  platform/ping-worker/tsconfig.json
  platform/ping-worker/wrangler.toml
  yarn.lock
Labels: enhancement

#985 feat(address): introduce `@kubelt/address-worker` package
  platform/address-worker/.eslintrc.json
  platform/address-worker/.gitignore
  platform/address-worker/.prettierrc.json
  platform/address-worker/package.json
  platform/address-worker/src/core.ts
  platform/address-worker/src/index.ts
  platform/address-worker/src/jsonrpc.ts
  platform/address-worker/src/openrpc.json
  platform/address-worker/src/types.ts
  platform/address-worker/src/utils.ts
  platform/address-worker/tsconfig.json
  platform/address-worker/wrangler.toml
  platform/passport-worker/.eslintrc.json
  platform/passport-worker/.gitignore
  platform/passport-worker/.prettierrc.json
  platform/passport-worker/package.json
  platform/passport-worker/src/constants.ts
  platform/passport-worker/src/core.ts
  platform/passport-worker/src/index.ts
  platform/passport-worker/src/openrpc.json
  platform/passport-worker/src/types.ts
  platform/passport-worker/tsconfig.json
  platform/passport-worker/wrangler.toml
  platform/ping-worker/.eslintrc.json
  platform/ping-worker/.gitignore
  platform/ping-worker/.prettierrc.json
  platform/ping-worker/package.json
  platform/ping-worker/src/core.ts
  platform/ping-worker/src/index.ts
  platform/ping-worker/src/openrpc.json
  platform/ping-worker/src/types.ts
  platform/ping-worker/tsconfig.json
  platform/ping-worker/wrangler.toml
  platform/worker-commons/src/routers/core.ts
  platform/worker-commons/src/utils/getCoreId.ts
  yarn.lock
Labels: enhancement

#1007 feat(nftar): Add tests and new image generator.
  projects/nftar/Dockerfile
  projects/nftar/package.json
  projects/nftar/src/app.js
  projects/nftar/tests/datauri.js
Labels: enhancement

#1009 fix(threeid): expand modal real estate
  apps/threeid/app/components/modal/Modal.tsx
  apps/threeid/app/components/nft-collection/ModaledNft.tsx
  apps/threeid/app/components/nft-collection/NftModal.tsx
Labels: enhancement

#1010 feat(threeid): profile skeleton loader
  apps/threeid/app/components/nft-collection/ProfileNftCollection.tsx
Labels: enhancement

#1008 feat(sb): init app cores from fixture data
  packages/openrpc/component/index.ts
  platform/starbase/.gitignore
  platform/starbase/curl/kb_initPlatform.json
  platform/starbase/package.json
  platform/starbase/src/index.ts
  platform/starbase/wrangler.toml
Labels: enhancement

#1012 feat(nftar): Fix OG:Image Rendering
  projects/nftar/Dockerfile
Labels: enhancement

#1013 fix(threeid): modaled nft cursor
  apps/threeid/app/components/nft-collection/ModaledNft.tsx
Labels: bug, enhancement

#1015 chore(sb): prettify, lint, and generate docs for library package
  .gitignore
  apps/console/package.json
  packages/cores/application/package.json
  packages/cores/contract/package.json
  packages/cores/user/package.json
  packages/openrpc/.gitignore
  packages/openrpc/api-extractor.json
  packages/openrpc/component/index.ts
  packages/openrpc/constants.ts
  packages/openrpc/docs/openrpc.api.md
  packages/openrpc/impl/client.ts
  packages/openrpc/impl/context.ts
  packages/openrpc/impl/index.ts
  packages/openrpc/impl/jsonrpc.ts
  packages/openrpc/impl/router.ts
  packages/openrpc/impl/schema.ts
  packages/openrpc/impl/scopes.ts
  packages/openrpc/impl/utility.ts
  packages/openrpc/index.ts
  packages/openrpc/middleware/analytics.ts
  packages/openrpc/middleware/authenticate.ts
  packages/openrpc/middleware/datadog.ts
  packages/openrpc/middleware/geolocation.ts
  packages/openrpc/middleware/local.ts
  packages/openrpc/middleware/oort.ts
  packages/openrpc/package.json
  packages/openrpc/tsconfig.json
  platform/starbase/package.json
  platform/starbase/src/index.ts
  platform/starbase/src/schema.ts
  platform/starbase/src/secret.ts
  yarn.lock
Labels: enhancement

#1016 chore(console): update deps, fix a build error
  apps/console/package.json
  apps/yarn.lock
Labels: dependencies

#1021 feat(threeid): nft modal skeleton
  apps/threeid/app/components/nft-collection/NftModal.tsx
Labels: enhancement

#1025 chore(workspaces): update `yarn.lock`
  yarn.lock
Labels: dependencies

#1022 feat(access): introduce `@kubelt/access-worker` package
  platform/access-worker/.eslintrc.json
  platform/access-worker/.gitignore
  platform/access-worker/.prettierrc.json
  platform/access-worker/package.json
  platform/access-worker/src/access.ts
  platform/access-worker/src/authorization.ts
  platform/access-worker/src/constants.ts
  platform/access-worker/src/index.ts
  platform/access-worker/src/jsonrpc.ts
  platform/access-worker/src/openrpc.json
  platform/access-worker/src/types.ts
  platform/access-worker/tsconfig.json
  platform/access-worker/wrangler.toml
  yarn.lock
Labels: enhancement

#1029 Add CORS headers.
  apps/threeid/app/routes/$profile.json.tsx
Labels: enhancement

#1031 fix(access): rename `account` service binding
  platform/access/src/types.ts
  platform/access/wrangler.toml
Labels: bug

#1027 feat(sb): bind to passport service to authenticate calls
  package.json
  platform/starbase/package.json
  platform/starbase/src/index.ts
  platform/starbase/wrangler.toml
  yarn.lock
Labels: enhancement

#1038 fix(access): generate durable object id from name
  platform/access/src/jsonrpc.ts
Labels: bug

#1035 fix(threeid): varifixes
  apps/threeid/app/components/head-nav/index.tsx
  apps/threeid/app/routes/$profile.tsx
  apps/threeid/app/routes/account.tsx
  apps/threeid/app/routes/account/settings/profile.tsx
Labels: bug, enhancement

#1037 fix(threeid): tailwind config relative modules
  apps/threeid/tailwind.config.js
Labels: bug, enhancement

#1044 chore(platform.access): improvements
  platform/access/package.json
  platform/access/src/access.ts
  platform/access/src/authorization.ts
  platform/access/src/jsonrpc.ts
  platform/access/src/types.ts
  platform/access/wrangler.toml
  yarn.lock
Labels: enhancement

#1048 chore(workspaces): minor improvements
  .github/workflows/main-console.yaml
  .github/workflows/main-galaxy.yaml
  .github/workflows/main-icons.yaml
  .github/workflows/main-nftar.yaml
  .github/workflows/main-oort.yaml
  .github/workflows/main-passport.yaml
  .github/workflows/main-redeem.yaml
  .github/workflows/main-smartcontracts.yaml
  .github/workflows/main-starbase.yaml
  .github/workflows/main-threeid.yaml
  .github/workflows/next-console.yaml
  .github/workflows/next-galaxy.yaml
  .github/workflows/next-icons.yaml
  .github/workflows/next-oort.yaml
  .github/workflows/next-passport.yaml
  .github/workflows/next-redeem.yaml
  .github/workflows/next-starbase.yaml
  .github/workflows/next-threeid.yaml
  .github/workflows/pr-apps.yaml
  .github/workflows/pr-packages.yaml
  .github/workflows/pr-platform.yaml
  .github/workflows/pr-projects.yaml
  .github/workflows/pr-smartcontracts.yaml
  .github/workflows/release-console.yaml
  .github/workflows/release-galaxy.yaml
  .github/workflows/release-icons.yaml
  .github/workflows/release-oort.yaml
  .github/workflows/release-passport.yaml
  .github/workflows/release-redeem.yaml
  .github/workflows/release-starbase.yaml
  .github/workflows/release-threeid.yaml
Labels: dependencies

#1045 feat(sb): misc improvements
  packages/cores/application/index.ts
  packages/cores/application/schema.ts
  packages/cores/user/index.ts
  packages/cores/user/schema.ts
  packages/openrpc/component/index.ts
  packages/openrpc/constants.ts
  packages/openrpc/impl/client.ts
  packages/openrpc/impl/index.ts
  packages/openrpc/impl/router.ts
  packages/openrpc/index.ts
  platform/starbase/curl/kb_appAuthCheck.json
  platform/starbase/curl/kb_appAuthInfo.json
  platform/starbase/curl/kb_appProfile.json
  platform/starbase/curl/kb_appStore.json
  platform/starbase/package.json
  platform/starbase/src/index.ts
  platform/starbase/src/schema.ts
  platform/starbase/src/token.ts
  yarn.lock
Labels: enhancement

#1049 chore(sb): add some fixture data
  platform/starbase/data/state/kv/FIXTURES/local-console
  platform/starbase/data/state/kv/FIXTURES/local-threeid
Labels: enhancement

#1059 feat(design): text
  apps/threeid/app/components/accounts/settings/PfpNftModal.tsx
  apps/threeid/app/components/head-nav/index.tsx
  apps/threeid/app/components/inputs/InputText.tsx
  apps/threeid/app/components/inputs/InputTextarea.tsx
  apps/threeid/app/components/invite-code/index.tsx
  apps/threeid/app/components/nft-collection/ModaledNft.tsx
  apps/threeid/app/components/nft-collection/NftModal.tsx
  apps/threeid/app/components/nft-collection/ProfileNftCollection.tsx
  apps/threeid/app/components/nft-collection/SelectableNft.tsx
  apps/threeid/app/components/profile/ProfileCard.tsx
  apps/threeid/app/components/sign-out-link/index.tsx
  apps/threeid/app/components/typography/Heading.tsx
  apps/threeid/app/components/typography/SectionHeading.tsx
  apps/threeid/app/components/typography/SectionHeadingSubtle.tsx
  apps/threeid/app/components/typography/SectionTitle.tsx
  apps/threeid/app/components/typography/SmallRegularBlock.tsx
  apps/threeid/app/root.tsx
  apps/threeid/app/routes/$profile.tsx
  apps/threeid/app/routes/account.tsx
  apps/threeid/app/routes/account/dashboard.tsx
  apps/threeid/app/routes/account/settings.tsx
  apps/threeid/app/routes/account/settings/profile.tsx
  apps/threeid/app/routes/onboard/mint/index.tsx
  apps/threeid/app/routes/onboard/name.tsx
  apps/threeid/remix.env.d.ts
  packages/design-system/package.json
  packages/design-system/src/atoms/text/Text.documentation.mdx
  packages/design-system/src/atoms/text/Text.stories.tsx
  packages/design-system/src/atoms/text/Text.tsx
  packages/design-system/src/index.ts
  packages/design-system/src/styles/global.css
  packages/design-system/tailwind.config.js
Labels: enhancement

#1058 chore: save changes to .yarnrc.yml after using upgrade-interactive
  .yarnrc.yml
Labels: enhancement

#1050 fix(nftar): Fix Cryptopunks 403 Error
  projects/nftar/src/app.js
  projects/nftar/src/utils.js
  projects/nftar/tests/datauri.js
  projects/nftar/tests/utils.test.js
Labels: bug

#1057 feat: shared package for security-related things
  packages/security/.eslintrc.json
  packages/security/.gitignore
  packages/security/api-extractor.json
  packages/security/docs/security.api.md
  packages/security/index.ts
  packages/security/package.json
  packages/security/scopes.ts
  packages/security/tsconfig.json
  platform/starbase/curl/kb_appScopes.json
  platform/starbase/package.json
  platform/starbase/src/index.ts
  platform/starbase/src/schema.ts
  yarn.lock
Labels: enhancement

#1061 feat(galaxy): Add Profile Migration Logic
  platform/galaxy/src/env.ts
  platform/galaxy/src/index.ts
  platform/galaxy/src/schema/resolvers/profile.ts
  platform/galaxy/src/schema/resolvers/utils/index.ts
  platform/galaxy/wrangler.toml
  platform/oort/src/packages/objects/objects.ts
  platform/oort/src/routes/core/context.ts
  platform/ping/wrangler.toml
Labels: enhancement

#1070 chore(workspaces): add yarn cache files
  .yarn/cache/@nomicfoundation-solidity-analyzer-darwin-arm64-npm-0.1.0-2a7a18bfb0-8.zip
  .yarn/cache/esbuild-darwin-arm64-npm-0.14.51-2e06e4188e-8.zip
  .yarn/cache/esbuild-darwin-arm64-npm-0.15.15-146f3e9e67-8.zip
  .yarn/cache/fsevents-patch-3340e2eb10-8.zip
  .yarn/cache/fsevents-patch-7450bc5e91-8.zip
  .yarn/cache/fsevents-patch-fcdf30aaca-8.zip
Labels: dependencies

#1063 feat(design): cover
  apps/threeid/app/routes/$profile.tsx
  packages/design-system/src/atoms/profile/avatar/Avatar.stories.tsx
  packages/design-system/src/atoms/profile/avatar/Avatar.tsx
  packages/design-system/src/atoms/profile/cover/Cover.stories.tsx
  packages/design-system/src/atoms/profile/cover/Cover.tsx
  packages/design-system/src/index.ts
Labels: enhancement

#1080 chore(commons): remove peer dependencies
  platform/access/package.json
  platform/account/package.json
  platform/address/package.json
  platform/commons/package.json
  platform/commons/src/routers/core.ts
  platform/commons/src/routers/cors.ts
  platform/commons/src/routers/index.ts
  platform/commons/src/utils/getCoreId.ts
  platform/commons/src/utils/index.ts
  platform/object/package.json
  platform/ping/package.json
  yarn.lock
Labels: dependencies

#1081 fix(address): resolve address from the worker
  platform/address/src/jsonrpc.ts
Labels: bug

#1093 chore(workspaces): use `npm-run-all`
  .yarn/cache/cross-spawn-npm-4.0.2-3c23494e5b-8ce57b3e11.zip
  .yarn/cache/event-stream-npm-3.3.4-5a4db234bf-80b467820b.zip
  .yarn/cache/from-npm-0.1.7-6dcf14a57d-b85125b789.zip
  .yarn/cache/lru-cache-npm-4.1.5-ede304cc43-4bb4b58a36.zip
  .yarn/cache/map-stream-npm-0.1.0-e44450fc62-38abbe4eb8.zip
  .yarn/cache/pause-stream-npm-0.0.11-d0e142313d-3c4a14052a.zip
  .yarn/cache/ps-tree-npm-1.2.0-3975e95bd6-e635dd00f5.zip
  .yarn/cache/pseudomap-npm-1.0.2-0d0e40fee0-856c0aae0f.zip
  .yarn/cache/split-npm-0.3.3-847dc2ba97-2e076634c9.zip
  .yarn/cache/stream-combiner-npm-0.0.4-0176779791-844b622cfe.zip
  .yarn/cache/yallist-npm-2.1.2-2e38c366a3-9ba9940920.zip
  .yarn/cache/yarn-run-all-npm-3.1.1-7705fb9583-e300c46b62.zip
  apps/console/package.json
  apps/package.json
  apps/passport/package.json
  apps/threeid/package.json
  package.json
  packages/cores/application/package.json
  packages/cores/contract/package.json
  packages/cores/user/package.json
  packages/design-system/package.json
  packages/openrpc/package.json
  packages/package.json
  packages/security/package.json
  platform/access-gateway/package.json
  platform/access/package.json
  platform/account/package.json
  platform/address/package.json
  platform/commons/package.json
  platform/galaxy/package.json
  platform/icons/package.json
  platform/object/package.json
  platform/oort/package.json
  platform/package.json
  platform/ping/package.json
  platform/starbase/package.json
  projects/package.json
  projects/redeem/package.json
  smartcontracts/package.json
  yarn.lock
Labels: dependencies

#1094 chore(starbase): add `prettier`
  platform/starbase/package.json
  yarn.lock
Labels: dependencies

#1095 chore(starbase): add `eslint`
  platform/starbase/package.json
  yarn.lock
Labels: dependencies

#1088 fix(platform): add `check` and `test` scripts
  platform/access-gateway/package.json
  platform/access/package.json
  platform/account/package.json
  platform/address/package.json
  platform/commons/package.json
  platform/object/package.json
  platform/ping/package.json
  platform/starbase/package.json
Labels: bug

#1099 fix(design): button
  apps/passport/app/components/authorization/Authorization.tsx
  apps/passport/app/components/connect-button/ConnectButton.scss
  apps/passport/app/components/connect-button/ConnectButton.tsx
  apps/passport/app/components/threeid-button/ThreeIdButton.tsx
  apps/passport/app/routes/authenticate/$address.sign.tsx
  packages/design-system/src/atoms/button/Button.module.css
  packages/design-system/src/atoms/button/Button.stories.jsx
  packages/design-system/src/atoms/button/Button.tsx
Labels: bug, enhancement
