Repository proofzero/rollupid, pull requests merged in 2022-07, with the labels that each got.

#499 feat(three-id): deploy to CloudFlare
  .github/workflows/next.yaml
  bb.edn
  bb/com/kubelt/cloudflare.clj
  bb/com/kubelt/cloudflare/asset.clj
  bb/com/kubelt/cloudflare/kv.clj
  bb/com/kubelt/deps.clj
  bb/com/kubelt/dot_env.clj
  bb/com/kubelt/edn.clj
  bb/com/kubelt/environ.clj
  bb/com/kubelt/git.clj
  bb/com/kubelt/github.clj
  bb/com/kubelt/github/secret.clj
  bb/com/kubelt/system.clj
  package-lock.json
  packages/sdk-clj/bb.edn
  packages/sdk-cljs/bb.edn
  packages/sdk-js/bb.edn
  packages/three-id/.gitignore
  packages/three-id/app.json
  packages/three-id/assets/adaptive-icon.png
  packages/three-id/assets/favicon.png
  packages/three-id/assets/icon.png
  packages/three-id/assets/splash.png
  packages/three-id/provider/kubelt.ts
  src/main/com/kubelt/sdk.cljs
  src/main/com/kubelt/sdk/v1/oort.cljs
  three-id/.env.example
  three-id/.gitignore
  three-id/README.md
  three-id/app.config.ts
  three-id/babel.config.js
  three-id/bb.edn
  three-id/package-lock.json
  three-id/package.json
  three-id/src/.gitkeep
  three-id/src/App.tsx
  three-id/src/assets/android-chrome-192x192.png
  three-id/src/assets/android-chrome-512x512.png
  three-id/src/assets/favicon-32x32.png
  three-id/src/assets/three-id-logo.svg
  three-id/src/hooks/account.ts
  three-id/src/index.ts
  three-id/src/provider/kubelt.ts
  three-id/src/provider/web3.ts
  three-id/src/screens/Auth.tsx
  three-id/src/screens/Gate.tsx
  three-id/src/screens/Landing.tsx
  three-id/src/screens/Layout.tsx
  three-id/tsconfig.json
  three-id/worker/.gitignore
  three-id/worker/package-lock.json
  three-id/worker/package.json
  three-id/worker/src/index.js
  three-id/worker/wrangler.toml.example
Labels: enhancement

#513 FEAT(claim): remove web3modal
  three-id/src/provider/web3.ts
  three-id/src/screens/Auth.tsx
  three-id/src/screens/Landing.tsx
  three-id/src/screens/Layout.tsx
Labels: enhancement

#515 FEAT(claim): remove redirect
  three-id/.env.example
  three-id/src/provider/kubelt.ts
  three-id/src/screens/Auth.tsx
Labels: enhancement

#516 feat(3iD): inject compile-time constants
  bb/com/kubelt/dot_env.clj
  three-id/bb.edn
Labels: enhancement

#509 FEAT(claim): Stored SDK in localStorage on succes auth to KBT
  three-id/src/provider/kubelt.ts
Labels: enhancement

#524 BUG(Landing): Non-web3 browser exception
  three-id/src/provider/web3.ts
Labels: bug

#522 FEAT(Gate): Add Try Different Wallet button
  three-id/package-lock.json
  three-id/package.json
  three-id/src/App.tsx
  three-id/src/provider/kubelt.ts
  three-id/src/provider/web3.ts
  three-id/src/screens/Auth.tsx
  three-id/src/screens/Gate.tsx
Labels: enhancement

#526 BUG(Favicon): Update logo asset
  three-id/src/assets/three-id-logo.png
Labels: bug

#531 BUG(3iD): Polish Tracker - Auth copy
  three-id/src/screens/Auth.tsx
Labels: bug, enhancement

#532 BUG(3iD): Polish Tracker - Splash screen
  three-id/package-lock.json
  three-id/package.json
  three-id/src/App.tsx
Labels: bug

#533 BUG(3iD): Polish Tracker - Clear account
  three-id/src/provider/web3.ts
Labels: bug

#527 chore(3iD): update build pipeline
  .actrc
  .github/workflows/develop.yaml
  .github/workflows/next.yaml
  .github/workflows/ref-docs.yaml
  .github/workflows/release.yaml
  .gitignore
  bb/com/kubelt/util.clj
  package-lock.json
  three-id/bb.edn
  three-id/package-lock.json
  three-id/package.json
Labels: enhancement

#536 chore(3iD): update dependencies
  three-id/package-lock.json
  three-id/package.json
Labels: dependencies

#538 fix(gha): update next pipeline
  .github/workflows/next.yaml
  bb.edn
  three-id/bb.edn
Labels: enhancement

#541 chore(3iD): update deps, tweak next workflow
  .github/workflows/next.yaml
  three-id/bb.edn
  three-id/package-lock.json
  three-id/package.json
Labels: enhancement, dependencies

#546 FEAT(DD): RUM session setup
  three-id/src/App.tsx
  three-id/src/analytics/datadog.ts
Labels: enhancement

#544 chore(3iD): update (and downgrade) deps
  three-id/package-lock.json
  three-id/package.json
Labels: enhancement

#556 CHORE(Three-id): Add navigation by path on web
  three-id/src/App.tsx
Labels: enhancement

#565 FEAT(Three-id): Clone CLJS Profile Settings screen
  src/main/com/kubelt/jsonspec/Profile.json
  src/main/com/kubelt/sdk/v1/oort.cljs
  src/main/com/kubelt/spec/profile.cljc
  src/test/com/kubelt/rpc/nfts_test.cljs
  three-id/README.md
  three-id/package-lock.json
  three-id/package.json
  three-id/src/App.tsx
  three-id/src/assets/three-id-logo-white.svg
  three-id/src/hooks/account.ts
  three-id/src/provider/kubelt.ts
  three-id/src/provider/web3.ts
  three-id/src/screens/AuthLayout.tsx
  three-id/src/screens/Layout.tsx
  three-id/src/screens/funnel/Gate.tsx
  three-id/src/screens/profile/Settings.tsx
  three-id/src/types/Profile.d.ts
  three-id/worker/src/index.js
Labels: enhancement

#568 CHORE(Three-id): Remove manual analytics
  three-id/src/analytics/datadog.ts
  three-id/src/screens/funnel/Auth.tsx
  three-id/src/screens/funnel/Gate.tsx
  three-id/src/screens/funnel/Landing.tsx
  three-id/src/screens/minting/Mint.tsx
  three-id/src/screens/profile/Settings.tsx
Labels: enhancement

#575 FEAT(Three-id): Check claims after succesful authentication
  src/main/com/kubelt/lib/rpc.cljs
  src/main/com/kubelt/sdk/v1/oort.cljs
  three-id/README.md
  three-id/src/hooks/account.ts
  three-id/src/hooks/sdkAuth.ts
  three-id/src/provider/kubelt.ts
  three-id/src/provider/web3.ts
  three-id/src/screens/AuthLayout.tsx
  three-id/src/screens/funnel/Auth.tsx
  three-id/src/screens/funnel/Gate.tsx
  three-id/src/screens/funnel/Landing.tsx
  three-id/src/screens/profile/Settings.tsx
Labels: enhancement

#600 CHORE(Three-id): Properly respond to try wallet
  three-id/src/analytics/datadog.ts
  three-id/src/hooks/account.ts
  three-id/src/hooks/sdkAuth.ts
  three-id/src/provider/kubelt.ts
  three-id/src/provider/web3.ts
  three-id/src/screens/funnel/Auth.tsx
  three-id/src/screens/funnel/Gate.tsx
  three-id/src/screens/funnel/Landing.tsx
  three-id/src/screens/profile/Settings.tsx
Labels: enhancement

#615 FEAT(Three-id): Rename project folder
  .github/workflows/develop.yaml
  .github/workflows/next.yaml
  .github/workflows/release.yaml
  3iD/.env.example
  3iD/.gitignore
  3iD/README.md
  3iD/app.config.ts
  3iD/babel.config.js
  3iD/bb.edn
  3iD/package-lock.json
  3iD/package.json
  3iD/src/.gitkeep
  3iD/src/App.tsx
  3iD/src/analytics/datadog.ts
  3iD/src/assets/foo.svg
  3iD/src/assets/three-id-logo-white.svg
  3iD/src/assets/three-id-logo.png
  3iD/src/assets/three-id-logo.svg
  3iD/src/hooks/account.ts
  3iD/src/hooks/sdkAuth.ts
  3iD/src/index.ts
  3iD/src/provider/kubelt.ts
  3iD/src/provider/web3.ts
  3iD/src/screens/AuthLayout.tsx
  3iD/src/screens/Layout.tsx
  3iD/src/screens/funnel/Auth.tsx
  3iD/src/screens/funnel/Gate.tsx
  3iD/src/screens/funnel/Landing.tsx
  3iD/src/screens/minting/Mint.tsx
  3iD/src/screens/profile/Details.tsx
  3iD/src/screens/profile/Settings.tsx
  3iD/src/types/Profile.d.ts
  3iD/tests/e2e/.eslintrc.js
  3iD/tests/e2e/specs/gate-allowed-spec.js
  3iD/tests/e2e/synpress.json
  3iD/tests/e2e/tsconfig.json
  3iD/tests/support/commands.js
  3iD/tests/support/index.js
  3iD/tsconfig.json
  3iD/worker/.gitignore
  3iD/worker/package-lock.json
  3iD/worker/package.json
  3iD/worker/src/index.js
  3iD/worker/wrangler.toml.example
  README.md
  bb.edn
Labels: enhancement

#620 chore(3iD): Fix webpack version mismatch due to expo-cli
  package-lock.json
  package.json
  src/main/com/kubelt/sdk.cljs
Labels: bug

#637 docs(claim): Add Authorization Guide and Update 3ID
  www/content/en/docs/guides/3ID.md
  www/content/en/docs/guides/authorization.md
Labels: documentation
