Repository proofzero/rollupid, pull requests merged in 2022-10, with the labels that each got.

#836 SPIKE(3iD-UI): Kitchensink
  threeid/app/components/inputs/InputText.tsx
  threeid/app/components/typography/Text.tsx
  threeid/app/routes/kitchensink.tsx
Labels: documentation, enhancement

#837 feat(nftar): Add Multiple Contract Types, Add Deprecations, Fix Dates
  nftar/.gitignore
  nftar/bin/local_smoke.sh
  nftar/index.js
  nftar/src/app.js
  nftar/src/utils.js
  nftar/tests/utils.test.js
Labels: bug, enhancement

#858 FIX(3iD): Use oort object package
  threeid/app/routes/account.tsx
  threeid/app/routes/account/index.tsx
  threeid/app/routes/onboard/mint/index.tsx
  threeid/app/routes/onboard/mint/load-voucher.tsx
  threeid/app/routes/onboard/name.tsx
Labels: enhancement

#854 FEAT(3iD): Unauth headnav
  threeid/app/components/head-nav/index.tsx
Labels: enhancement

#840 feat(crdt): Add $CRDT Upgradable Contract
  smartcontracts/eth/crdt/.gitattributes
  smartcontracts/eth/crdt/.github/workflows/main.yaml
  smartcontracts/eth/crdt/.github/workflows/pr.yaml
  smartcontracts/eth/crdt/.gitignore
  smartcontracts/eth/crdt/LICENSE.md
  smartcontracts/eth/crdt/contracts/CRDT.sol
  smartcontracts/eth/crdt/contracts/CRDTv2.sol
  smartcontracts/eth/crdt/crdt.config.ts
  smartcontracts/eth/crdt/crdt.networks.ts
  smartcontracts/eth/crdt/hardhat.config.ts
  smartcontracts/eth/crdt/package-lock.json
  smartcontracts/eth/crdt/package.json
  smartcontracts/eth/crdt/test/CRDT.ts
  smartcontracts/eth/hardhat.config.ts
  smartcontracts/eth/pfp-invites/.gitignore
  smartcontracts/eth/pfp-invites/LICENSE.md
  smartcontracts/eth/pfp-invites/README.md
  smartcontracts/eth/pfp-invites/assets/3ID_NFT_CARD_NO_BG.svg
  smartcontracts/eth/pfp-invites/balances.sh
  smartcontracts/eth/pfp-invites/bin/local_profile_smoke.sh
  smartcontracts/eth/pfp-invites/contracts/Invite.sol
  smartcontracts/eth/pfp-invites/contracts/PFP.sol
  smartcontracts/eth/pfp-invites/hardhat.config.ts
  smartcontracts/eth/pfp-invites/invite.config.ts
  smartcontracts/eth/pfp-invites/package-lock.json
  smartcontracts/eth/pfp-invites/package.json
  smartcontracts/eth/pfp-invites/plugin/InviteRuntimeField.ts
  smartcontracts/eth/pfp-invites/plugin/index.ts
  smartcontracts/eth/pfp-invites/plugin/type-extensions.ts
  smartcontracts/eth/pfp-invites/profile.config.ts
  smartcontracts/eth/pfp-invites/scripts/.gitkeep
  smartcontracts/eth/pfp-invites/test/Invite.ts
  smartcontracts/eth/pfp-invites/test/PFP.ts
  smartcontracts/eth/pfp-invites/tsconfig.json
Labels: enhancement

#863 fix(crdt): Move workflows to root.
  .github/workflows/main.yaml
  .github/workflows/next.yaml
  .github/workflows/pr.yaml
  smartcontracts/eth/crdt/.github/workflows/main.yaml
  smartcontracts/eth/crdt/.github/workflows/pr.yaml
Labels: enhancement

#838 FEAT(3iD-Profile): Public profile
  threeid/.env.example
  threeid/app/assets/No_NFT_Found.svg
  threeid/app/assets/book.svg
  threeid/app/assets/partners/opensea.svg
  threeid/app/assets/partners/polygon.svg
  threeid/app/assets/partners/rarible.svg
  threeid/app/assets/partners/superrare.svg
  threeid/app/components/buttons/ButtonAnchor.tsx
  threeid/app/components/head-nav/index.tsx
  threeid/app/components/profile/ProfileCard.tsx
  threeid/app/components/profile/ProfileNftCollection.scss
  threeid/app/components/profile/ProfileNftCollection.tsx
  threeid/app/helpers/gateway-from-ipfs.ts
  threeid/app/helpers/voucher.ts
  threeid/app/routes/$profile.json.tsx
  threeid/app/routes/$profile.tsx
  threeid/app/routes/kitchensink.tsx
  threeid/app/routes/nfts/index.tsx
  threeid/app/routes/onboard/mint/load-voucher.tsx
  threeid/app/utils/rpc.server.tsx
  threeid/package-lock.json
  threeid/package.json
Labels: enhancement

#864 FIX(3iD-Profile): Hide date on profile & rem logs
  threeid/app/components/profile/ProfileCard.tsx
  threeid/app/routes/$profile.json.tsx
  threeid/app/routes/$profile.tsx
Labels: bug

#866 fix(eth): Fixed a small bug in the ethereum hardhat config
  smartcontracts/eth/pfp-invites/hardhat.config.ts
Labels: bug

#881 FEAT(3ID): Align to Galaxy
  projects/threeid/.dev.vars.example
  projects/threeid/app/components/head-nav/index.tsx
  projects/threeid/app/helpers/voucher.ts
  projects/threeid/app/routes/$profile.json.tsx
  projects/threeid/app/routes/$profile.tsx
  projects/threeid/app/routes/account.tsx
  projects/threeid/app/routes/account/dashboard.tsx
  projects/threeid/app/routes/account/settings/profile.tsx
  projects/threeid/app/routes/onboard.tsx
  projects/threeid/app/routes/onboard/mint/index.tsx
  projects/threeid/app/routes/onboard/mint/load-voucher.tsx
  projects/threeid/app/routes/onboard/name.tsx
Labels: enhancement

#883 chore: use fixed versions for dependencies
  .yarnrc.yml
Labels: dependencies

#890 fix(oort): build production mode for `devnet` environment
  projects/oort/wrangler.toml
Labels: bug

#893 FEAT(3iD): Various feats
  projects/galaxy/src/schema/types/profile.ts
  projects/threeid/app/components/inputs/InputText.tsx
  projects/threeid/app/components/inputs/InputTextarea.tsx
  projects/threeid/app/components/profile/NftModal.tsx
  projects/threeid/app/components/profile/ProfileCard.tsx
  projects/threeid/app/components/profile/ProfileNftCollection.tsx
  projects/threeid/app/routes/account/settings/profile.tsx
  projects/threeid/app/routes/nfts/index.tsx
  projects/threeid/app/routes/onboard/name.tsx
Labels: enhancement

#868 feat(icons): add worker to support icon upload
  README.md
  projects/icons/.gitignore
  projects/icons/package.json
  projects/icons/src/index.ts
  projects/icons/tsconfig.json
  projects/icons/wrangler.toml
  projects/redeem/package.json
  yarn.lock
Labels: enhancement

#897 FIX(3iD): Pre deployment hacks
  projects/threeid/app/components/profile/ProfileCard.tsx
  projects/threeid/app/routes/$profile.tsx
  projects/threeid/app/routes/account/settings/profile.tsx
Labels: bug
