Repository proofzero/rollupid, pull requests merged in 2022-09, with the labels that each got.

#779 feat(mint): Add PFP Smart Contract Support
  eth/.gitignore
  eth/LICENSE.md
  eth/README.md
  eth/assets/3ID_NFT_CARD_NO_BG.svg
  eth/balances.sh
  eth/bin/local_profile_smoke.sh
  eth/contracts/Invite.sol
  eth/contracts/PFP.sol
  eth/hardhat.config.ts
  eth/invite.config.ts
  eth/invite/.gitignore
  eth/invite/test/Lock.ts
  eth/package-lock.json
  eth/package.json
  eth/plugin/InviteRuntimeField.ts
  eth/plugin/index.ts
  eth/plugin/type-extensions.ts
  eth/profile.config.ts
  eth/scripts/.gitkeep
  eth/test/Invite.ts
  eth/test/PFP.ts
  eth/tsconfig.json
  nftar/src/app.js
Labels: enhancement

#790 fix(pfp): Updated unit tests to new contract interface.
  eth/test/PFP.ts
Labels: enhancement

#796 feat(nftar): Update NFTar Metadata
  eth/bin/local_profile_smoke.sh
  eth/profile.config.ts
  nftar/src/app.js
Labels: enhancement

#797 fix(build): Dependency Fix
  package-lock.json
  package.json
Labels: enhancement

#806 feat(pfp): Disable transfers and add test for same.
  eth/contracts/PFP.sol
  eth/test/PFP.ts
Labels: enhancement

#807 fix(pfp): Remove debug output from tests.
  eth/test/PFP.ts
Labels: enhancement

#810 fix(pfp): Fix build warnings.
  eth/contracts/PFP.sol
Labels: enhancement

#800 FEAT(3iD): Onboarding wizard
  threeid/.env.example
  threeid/app/assets/abi/mintpfp.json
  threeid/app/assets/ens.png
  threeid/app/assets/onboard/current.png
  threeid/app/assets/onboard/next.png
  threeid/app/assets/onboard/pre.png
  threeid/app/components/buttons/Button.tsx
  threeid/app/components/typography/Text.tsx
  threeid/app/routes/account.tsx
  threeid/app/routes/auth.tsx
  threeid/app/routes/auth/gate/$address.tsx
  threeid/app/routes/auth/sign/$address.tsx
  threeid/app/routes/onboard.tsx
  threeid/app/routes/onboard/ens/index.tsx
  threeid/app/routes/onboard/ens/lookup-address.tsx
  threeid/app/routes/onboard/mint/index.tsx
  threeid/app/routes/onboard/mint/load-voucher.tsx
  threeid/app/routes/onboard/nickname/index.tsx
  threeid/app/styles/onboard.scss
  threeid/package.json
Labels: enhancement

#814 FIX(3iD): Move onboard check to account
  threeid/app/routes/account.tsx
  threeid/app/routes/auth.tsx
  threeid/app/routes/auth/gate/$address.tsx
  threeid/app/routes/auth/sign/$address.tsx
  threeid/app/routes/onboard.tsx
  threeid/app/routes/onboard/nickname/index.tsx
Labels: enhancement

#815 FEAT(3iD): Move onboard state from Oort to BFF
  threeid/app/routes/account.tsx
  threeid/package.json
Labels: enhancement

#816 FIX(3iD): Remove Oort onboarded state
  threeid/app/routes/onboard.tsx
Labels: bug

#817 FEAT(3iD): Mint PFP Token persist
  threeid/app/routes/onboard/mint/index.tsx
  threeid/app/routes/onboard/mint/load-voucher.tsx
  threeid/app/routes/onboard/nickname/index.tsx
Labels: enhancement

#819 FEAT(3iD): Adapt mint cache
  threeid/app/routes/auth/gate/$address.tsx
  threeid/app/routes/onboard.tsx
  threeid/app/routes/onboard/mint/index.tsx
  threeid/app/routes/onboard/mint/load-voucher.tsx
  threeid/app/routes/onboard/nickname/index.tsx
Labels: enhancement

#818 FEAT(3iD): ENS Update
  threeid/app/routes/onboard/ens/index.tsx
Labels: enhancement

#813 feat(nftar): Probability and Metadata Updates
  eth/README.md
  eth/bin/local_profile_smoke.sh
  eth/profile.config.ts
  nftar/README.md
  nftar/bin/local_smoke.sh
  nftar/index.js
  nftar/package-lock.json
  nftar/package.json
  nftar/src/app.js
  nftar/src/probability.js
  nftar/src/traits.js
  nftar/src/utils.js
  nftar/src/views/nftar.js
  nftar/tests/utils.test.js
Labels: enhancement

#827 FIX(3iD Wizard): Quickfixes
  threeid/app/assets/onboard/current.png
  threeid/app/assets/onboard/next.png
  threeid/app/assets/onboard/pre.png
  threeid/app/components/buttons/Button.scss
  threeid/app/components/buttons/Button.tsx
  threeid/app/components/buttons/ButtonAnchor.tsx
  threeid/app/routes/onboard/ens.tsx
  threeid/app/routes/onboard/mint/index.tsx
  threeid/app/routes/onboard/nickname.tsx
  threeid/app/styles/onboard.scss
Labels: bug, enhancement

#828 CHORE(3iD): Replace nickname
  threeid/app/routes/account.tsx
  threeid/app/routes/account/index.tsx
  threeid/app/routes/onboard.tsx
  threeid/app/routes/onboard/ens.tsx
  threeid/app/routes/onboard/mint/index.tsx
  threeid/app/routes/onboard/name.tsx
Labels: enhancement

#829 FEAT(3iD-UI): Button focus & disabled
  threeid/app/components/buttons/Button.scss
  threeid/app/components/buttons/Button.tsx
  threeid/app/components/buttons/index.ts
Labels: enhancement

#833 fix(nftar): Add proper Alchemy API KEY envvar name.
  nftar/index.js
Labels: enhancement
