Repository proofzero/rollupid, pull requests merged in 2023-02, with the labels that each got.

#1529 feat(address): oauth refresh token
  .github/workflows/main-address.yaml
  .github/workflows/next-address.yaml
  .github/workflows/release-address.yaml
  platform/address/.dev.vars.example
  platform/address/src/context.ts
  platform/address/src/jsonrpc/methods/getAddressProfile.ts
  platform/address/src/jsonrpc/validators/oauth.ts
  platform/address/src/nodes/apple.ts
  platform/address/src/nodes/google.ts
  platform/address/src/nodes/microsoft.ts
  platform/address/src/nodes/oauth.ts
  platform/address/src/types.ts
Labels: enhancement

#1574 fix(address): set the profile type predicate in the schema
  platform/address/src/jsonrpc/methods/getAddressProfile.ts
  platform/address/src/jsonrpc/validators/oauth.ts
  platform/address/src/jsonrpc/validators/profile.ts
Labels: bug

#1586 fix(profile): upload OG image
  apps/profile/app/routes/account/settings/profile/image-upload-url.tsx
Labels: bug

#1589 BUG(Profile): deleting OF image gets me 404 page
  platform/images/src/jsonrpc/methods/getOgImage.ts
Labels: bug

#1596 BUG(console): missing copy icon
  apps/console/app/components/Applications/Auth/ApplicationAuth.tsx
  apps/console/app/components/Applications/Dashboard/ApplicationDashboard.tsx
Labels: bug, enhancement

#1592 chore(profile): add Error/Catch boundry to /auth/callback
  apps/passport/app/routes/authenticate.tsx
  apps/passport/app/routes/authenticate/apple/callback.ts
  apps/passport/app/routes/authenticate/github/callback.ts
  apps/passport/app/routes/authenticate/google/callback.ts
  apps/passport/app/routes/authenticate/microsoft/callback.ts
  apps/passport/app/routes/authenticate/twitter/callback.ts
  apps/passport/public/favicon.ico
Labels: enhancement

#1614 fix(profile): compare the expiration time in milliseconds
  apps/profile/app/utils/session.server.tsx
Labels: bug

#1641 fix(images): microsoft pfp cache upload
  apps/passport/app/utils/cacheImageToCF.server.ts
  platform/images/src/jsonrpc/methods/uploadImageBlob.ts
  platform/images/src/jsonrpc/router.ts
Labels: bug

#1681 chore(passport): remove Pepe from error pages
  apps/passport/app/root.tsx
  apps/passport/app/routes/authenticate.tsx
  packages/design-system/src/pages/error/ErrorPage.tsx
Labels: enhancement

#1682 fix(profile): Value JS error in when editing links
  apps/profile/app/routes/account/settings/links.tsx
Labels: bug

#1693 chore(profile): updates navbar to v2
  apps/profile/app/components/addresses/AddressListItem.tsx
  apps/profile/app/components/head-nav/index.tsx
  apps/profile/app/components/profile/cover/Cover.tsx
  apps/profile/app/routes/$type.$address.tsx
  apps/profile/app/routes/$type.$address/account.tsx
  apps/profile/app/routes/$type.$address/index.tsx
  apps/profile/app/routes/account.tsx
  apps/profile/app/routes/account/connections/index.tsx
  apps/profile/app/routes/account/connections/order.tsx
  apps/profile/app/routes/account/connections/rename.tsx
  apps/profile/app/routes/account/dashboard.tsx
  apps/profile/app/routes/account/gallery.tsx
  apps/profile/app/routes/account/links.tsx
  apps/profile/app/routes/account/profile.tsx
  apps/profile/app/routes/account/profile/image-upload-url.tsx
  apps/profile/app/routes/account/profile/update-cover.tsx
  apps/profile/app/routes/account/settings.tsx
  apps/profile/app/routes/account/settings/index.tsx
  apps/profile/app/routes/account/settings/integrations.tsx
Labels: enhancement

#1697 fix(galaxy): double apply urn prefix
  platform/galaxy/src/schema/resolvers/nfts.ts
Labels: bug

#1701 chore(profile): mobile cta
  apps/profile/app/routes/account/dashboard.tsx
Labels: bug, enhancement

#1707 fix(passport): change favicon to client id icon when present so wallet and browser shows branded 3rd party logo
  apps/passport/app/root.tsx
  apps/passport/app/routes/authenticate.tsx
  apps/passport/app/routes/authenticate/index.tsx
  apps/passport/app/web3/lazyAuth.tsx
  apps/passport/public/favicon.ico
Labels: bug, enhancement

#1708 fix(passport): console params session should not expire
  apps/passport/app/root.tsx
  apps/passport/app/session.server.ts
Labels: bug, enhancement

#1718 feat(passport): discord oauth client environment variables
  .github/workflows/main-address.yaml
  .github/workflows/main-passport.yaml
  .github/workflows/next-address.yaml
  .github/workflows/next-passport.yaml
  .github/workflows/release-address.yaml
  .github/workflows/release-passport.yaml
Labels: enhancement

#1588 chore(galaxy, profile): nft optimization
  apps/profile/app/components/accounts/PfpNftModal.tsx
  apps/profile/app/components/addresses/AddressList.stories.tsx
  apps/profile/app/components/nfts/grid/filtered/index.tsx
  apps/profile/app/components/nfts/grid/unfiltered/index.tsx
  apps/profile/app/helpers/nfts.ts
  apps/profile/app/root.tsx
  apps/profile/app/routes/$type.$address.tsx
  apps/profile/app/routes/$type.$address/collections/$collection.tsx
  apps/profile/app/routes/$type.$address/collections/index.tsx
  apps/profile/app/routes/$type.$address/gallery.tsx
  apps/profile/app/routes/account/gallery.tsx
  apps/profile/app/routes/account/profile/image-upload-url.tsx
  apps/profile/app/routes/nfts/galleryFromD1.tsx
  packages/alchemy-client/index.ts
  packages/galaxy-client/gql/account.graphql
  packages/galaxy-client/gql/nfts.graphql
  packages/galaxy-client/index.ts
  platform/account/src/jsonrpc/methods/getGallery.ts
  platform/account/src/jsonrpc/validators/profile.ts
  platform/galaxy/src/schema/resolvers/account.ts
  platform/galaxy/src/schema/resolvers/nfts.ts
  platform/galaxy/src/schema/resolvers/utils/index.ts
  platform/galaxy/src/schema/resolvers/utils/nfts.ts
  platform/galaxy/src/schema/types/nfts.ts
  platform/images/src/jsonrpc/methods/getOgImage.ts
Labels: enhancement

#1732 bug(passport): connect account enters authorize flow
  apps/passport/app/routes/connect/index.tsx
  apps/passport/app/utils/authenticate.server.ts
Labels: bug

#1716 feat(profile): disconnect address in connected address screen
  apps/profile/app/routes/account/connections/disconnect.tsx
  apps/profile/app/routes/account/connections/index.tsx
  packages/galaxy-client/gql/account.graphql
  packages/galaxy-client/index.ts
  platform/galaxy/src/schema/resolvers/account.ts
  platform/galaxy/src/schema/types/account.ts
Labels: enhancement

#1770 chore(profile): dismiss welcome prompt
  apps/profile/app/components/cta/cta.tsx
  apps/profile/app/routes/account/dashboard.tsx
  apps/profile/app/utils/cta.client.ts
Labels: enhancement

#1779 fix(access): fix storage transaction calls
  platform/access/src/nodes/access.ts
Labels: bug

#1797 fix(access): set current time as the issue time properly
  platform/access/src/nodes/access.ts
Labels: bug

#1803 feat(profile): improve the connect address flow
  apps/passport/app/routes/connect/$address/sign.tsx
  apps/passport/app/routes/connect/discord/callback.ts
  apps/passport/app/routes/connect/github/callback.ts
  apps/passport/app/routes/connect/google/callback.ts
  apps/passport/app/routes/connect/microsoft/callback.ts
  apps/passport/app/routes/connect/twitter/callback.ts
  apps/passport/app/utils/authenticate.server.ts
  apps/profile/app/routes/account/connections/index.tsx
  platform/address/src/jsonrpc/methods/resolveAccount.ts
  platform/address/src/jsonrpc/methods/verifyNonce.ts
Labels: enhancement

#1809 fix(passport): handle-empty-app-data-in-sign-flow
  apps/passport/app/routes/connect/$address/sign.tsx
Labels: bug

#1709 feat(profile): Applications listing and revocation modal
  apps/profile/app/routes/account.tsx
  apps/profile/app/routes/account/applications/index.tsx
  apps/profile/app/routes/account/dashboard.tsx
  apps/profile/app/routes/api/apps/$clientId/scopes.tsx
  apps/profile/app/routes/api/apps/index.tsx
  packages/design-system/src/atoms/buttons/common.tsx
  packages/galaxy-client/gql/account.graphql
  packages/galaxy-client/gql/apps.graphql
  packages/galaxy-client/index.ts
  packages/security/scopes.ts
  platform/access/src/jsonrpc/methods/getAuthorizedAppScopes.ts
  platform/access/src/jsonrpc/router.ts
  platform/access/src/nodes/access.ts
  platform/galaxy/src/schema/index.ts
  platform/galaxy/src/schema/resolvers/account.ts
  platform/galaxy/src/schema/resolvers/app.ts
  platform/galaxy/src/schema/resolvers/index.ts
  platform/galaxy/src/schema/types/account.ts
  platform/galaxy/src/schema/types/app.ts
  platform/galaxy/src/schema/types/index.ts
Labels: enhancement
