Repository proofzero/rollupid, pull requests merged in 2023-03, with the labels that each got.

#1818 bug(profile): complete profile cta still shows after updating one field
  apps/profile/app/utils/cta.client.ts
Labels: bug

#1816 chore(passport): mobile view for auth screen update
  apps/passport/app/components/authentication/Authentication.tsx
Labels: enhancement

#1817 chore(passport): connect button show who is connected
  apps/passport/app/components/connect-button/ConnectButton.tsx
Labels: enhancement

#1823 feat(design-system): Toast messages
  apps/console/app/components/Applications/Auth/ApplicationAuth.tsx
  apps/console/app/components/Applications/Dashboard/ApplicationDashboard.tsx
  apps/console/app/routes/apps/$clientId.tsx
  apps/console/package.json
  apps/profile/app/routes/account.tsx
  apps/profile/app/routes/account/connections/index.tsx
  apps/profile/app/routes/account/gallery.tsx
  apps/profile/package.json
  packages/design-system/package.json
  packages/design-system/src/atoms/toast/Toast.tsx
  packages/design-system/src/atoms/toast/ToastError.tsx
  packages/design-system/src/atoms/toast/ToastInfo.tsx
  packages/design-system/src/atoms/toast/ToastSuccess.tsx
  packages/design-system/src/atoms/toast/ToastWarning.tsx
  packages/design-system/src/atoms/toast/ToastWithLink.tsx
  packages/design-system/src/atoms/toast/index.tsx
  packages/design-system/src/atoms/toast/toast.stories.tsx
  yarn.lock
Labels: enhancement

#1829 fix(profile): update access token in the user session data directly
  apps/profile/app/utils/session.server.tsx
Labels: bug

#1828 feat(passport): social login not displaying loading bar
  apps/passport/app/components/authentication/Authentication.stories.mdx
  apps/passport/app/components/authentication/Authentication.tsx
  apps/passport/app/components/connect-oauth-button/index.tsx
  apps/passport/app/routes/authenticate/index.tsx
Labels: enhancement

#1831 bug(profile): address rename not working
  apps/profile/app/routes/account/connections/rename.tsx
Labels: bug

#1854 fix(passport): fix the account urn value returned by `resolveAccount` method
  apps/passport/app/routes/connect/apple/callback.ts
Labels: bug

#1859 fix(profile): fix redirects if session checks fail
  apps/profile/app/utils/session.server.tsx
Labels: bug

#1864 chore(passport): change gradient to new image
  apps/passport/app/assets/auth-side-graphics.svg
  apps/passport/app/routes/authenticate.tsx
Labels: enhancement

#1863 chore(storybook): date fields always asking for review
  apps/console/app/components/Applications/ApplicationList.stories.tsx
  apps/console/app/components/Applications/ApplicationListItem.stories.tsx
  apps/console/app/components/Applications/Auth/ApplicationAuth.stories.tsx
  apps/console/app/components/Applications/Dashboard/ApplicationDashboard.stories.tsx
  apps/console/app/components/Applications/LoginsPanel/LoginsPanel.stories.tsx
  apps/profile/app/components/addresses/AddressList.stories.tsx
  apps/profile/app/components/addresses/AddressListItem.stories.tsx
  packages/design-system/src/atoms/profile/avatar/Avatar.stories.tsx
  packages/design-system/src/placeholders/rollup/b64.ts
  packages/design-system/src/placeholders/rollup/blue.svg
  packages/design-system/src/placeholders/rollup/gray.svg
  packages/design-system/src/placeholders/rollup/green.svg
Labels: bug, documentation

#1862 bug(profile): make dashboard connected accounts match connected accounts edit page
  apps/profile/app/helpers/profile.ts
  apps/profile/app/routes/account/connections/index.tsx
  apps/profile/app/routes/account/dashboard.tsx
Labels: bug, enhancement

#1874 bug(profile): rename accounts
  apps/profile/app/routes/account/connections/rename.tsx
Labels: bug

#1878 chore(apps): NODE_ENV=development
  .github/workflows/main-console.yaml
  .github/workflows/main-passport.yaml
  .github/workflows/main-profile.yaml
  .yarn/cache/env-cmd-npm-10.1.0-85470635d6-efef550742.zip
  apps/console/.dev.env
  apps/console/package.json
  apps/passport/.dev.env
  apps/passport/package.json
  apps/profile/.dev.env
  apps/profile/package.json
  yarn.lock
Labels: dx

#1886 chore(dx): server and inspector port numbers
  apps/console/wrangler.toml
  apps/passport/wrangler.toml
  apps/profile/wrangler.toml
  platform/access/wrangler.toml
  platform/account/wrangler.toml
  platform/address/wrangler.toml
  platform/edges/wrangler.toml
  platform/galaxy/wrangler.toml
  platform/images/wrangler.toml
  platform/starbase/wrangler.toml
Labels: dx

#1887 chore(platform): NODE_ENV=development
  .github/workflows/main-access.yaml
  .github/workflows/main-account.yaml
  .github/workflows/main-address.yaml
  .github/workflows/main-edges.yaml
  .github/workflows/main-galaxy.yaml
  .github/workflows/main-images.yaml
  .github/workflows/main-starbase.yaml
  platform/access/.dev.env
  platform/access/package.json
  platform/account/.dev.env
  platform/account/package.json
  platform/address/.dev.env
  platform/address/package.json
  platform/edges/.dev.env
  platform/edges/package.json
  platform/galaxy/.dev.env
  platform/galaxy/package.json
  platform/images/.dev.env
  platform/images/package.json
  platform/starbase/.dev.env
  platform/starbase/package.json
  yarn.lock
Labels: dx

#1879 feat(console): early access front end
  apps/console/.gitignore
  apps/console/app/assets/early/audience.svg
  apps/console/app/assets/early/billing.css
  apps/console/app/assets/early/blockchain.svg
  apps/console/app/assets/early/designer.webp
  apps/console/app/assets/early/domain.svg
  apps/console/app/assets/early/kyc.svg
  apps/console/app/assets/early/messaging.svg
  apps/console/app/assets/early/team.svg
  apps/console/app/components/EarlyAccess/EarlyAccessPanel.tsx
  apps/console/app/components/SiteHeader/index.tsx
  apps/console/app/components/SiteMenu/index.tsx
  apps/console/app/routes/apps/$clientId/audience.tsx
  apps/console/app/routes/apps/$clientId/billing.tsx
  apps/console/app/routes/apps/$clientId/blockchain.tsx
  apps/console/app/routes/apps/$clientId/designer.tsx
  apps/console/app/routes/apps/$clientId/domain.tsx
  apps/console/app/routes/apps/$clientId/kyc.tsx
  apps/console/app/routes/apps/$clientId/messaging.tsx
  apps/console/app/routes/apps/$clientId/team.tsx
  apps/console/app/styles/.gitignore
  apps/console/package.json
  apps/passport/package.json
  apps/profile/package.json
  packages/design-system/src/atoms/form/PreLabledInput.tsx
  packages/design-system/src/atoms/pills/FeaturePill.stories.tsx
  packages/design-system/src/atoms/pills/FeaturePill.tsx
Labels: enhancement

#1908 feat(passport): login screen with logged in user
  apps/console/app/utilities/session.server.tsx
  apps/passport/app/components/authentication/Authentication.tsx
  apps/passport/app/components/connect-button/ConnectButton.tsx
  apps/passport/app/root.tsx
  apps/passport/app/routes/authenticate.tsx
  apps/passport/app/routes/authenticate/$clientId.tsx
  apps/passport/app/routes/authenticate/index.tsx
  apps/passport/app/routes/authorize.tsx
  apps/passport/app/routes/authorize/index.tsx
  apps/passport/app/routes/connect/$address/sign.tsx
  apps/passport/app/routes/connect/apple/callback.ts
  apps/passport/app/routes/connect/discord/callback.ts
  apps/passport/app/routes/connect/github/callback.ts
  apps/passport/app/routes/connect/google/callback.ts
  apps/passport/app/routes/connect/microsoft/callback.ts
  apps/passport/app/routes/connect/twitter/callback.ts
  apps/passport/app/routes/signout.tsx
  apps/passport/app/session.server.ts
  apps/passport/app/utils/authenticate.server.ts
  apps/passport/bindings.d.ts
  apps/passport/package.json
  apps/profile/app/components/head-nav/index.tsx
  apps/profile/app/components/hean-nav-links/index.tsx
  apps/profile/app/routes/account.tsx
  apps/profile/app/routes/account/connections/index.tsx
  apps/profile/app/routes/auth/index.tsx
  apps/profile/app/routes/signout.tsx
  docs/guides/authenticating-users-in-your-app.md
  platform/address/src/jsonrpc/methods/resolveAccount.ts
  platform/address/src/jsonrpc/methods/verifyNonce.ts
  yarn.lock
Labels: enhancement

#1921 fix(passport): fix passport image panel on small screens
  apps/passport/app/components/authentication/Authentication.tsx
  apps/passport/app/routes/authenticate.tsx
Labels: bug

#1938 chore(console): links to documentation
  apps/console/app/components/DocumentationBadge/DocumentationBadge.stories.tsx
  apps/console/app/components/DocumentationBadge/index.tsx
  apps/console/app/components/EarlyAccess/EarlyAccessPanel.tsx
  apps/console/app/components/SiteMenu/index.tsx
  apps/console/app/routes/apps/$clientId.tsx
  apps/console/app/routes/apps/$clientId/audience.tsx
  apps/console/app/routes/apps/$clientId/auth.tsx
  apps/console/app/routes/apps/$clientId/billing.tsx
  apps/console/app/routes/apps/$clientId/blockchain.tsx
  apps/console/app/routes/apps/$clientId/designer.tsx
  apps/console/app/routes/apps/$clientId/domain.tsx
  apps/console/app/routes/apps/$clientId/index.tsx
  apps/console/app/routes/apps/$clientId/kyc.tsx
  apps/console/app/routes/apps/$clientId/messaging.tsx
  apps/console/app/routes/apps/$clientId/team.tsx
  apps/console/app/routes/apps/$clientId/users.tsx
  apps/console/app/routes/dashboard/index.tsx
Labels: enhancement, dx

#1949 fix(passport): provision appleid profile
  apps/passport/app/routes/authenticate/$clientId.tsx
  apps/passport/app/routes/connect/apple/callback.ts
  apps/passport/app/utils/authenticate.server.ts
  apps/profile/app/routes/account/connections/index.tsx
  platform/access/src/jsonrpc/validators/IdTokenProfileSchema.ts
  platform/access/src/utils/getIdTokenProfileFromAccount.ts
  platform/address/src/jsonrpc/validators/oauth.ts
  platform/address/src/jsonrpc/validators/profile.ts
Labels: bug

#1987 fix(profile): zod schema with optional gallery and links
  apps/profile/app/components/head-nav/nav-links.tsx
  apps/profile/app/components/side-nav/index.tsx
  apps/profile/app/validation.ts
Labels: bug
