Repository proofzero/rollupid, pull requests merged in 2023-04, with the labels that each got.

#2033 fix(passport): discord user icon
  apps/passport/app/utils/profile.ts
Labels: bug

#2101 fix(scopes): email scope check
  packages/security/persona.ts
Labels: bug

#2171 chore(passport): Tooltip copy for connected accounts in authz screen
  packages/security/scopes.ts
Labels: enhancement

#2159 feat(passport|console): Add application privacy policy and TOS to login, continue with and authz screens
  apps/console/app/routes/apps/$clientId/auth.tsx
  apps/console/app/types.ts
  apps/console/tests/console.spec.ts
  apps/passport/app/routes/authenticate/$clientId.tsx
  apps/passport/app/routes/authenticate/$clientId/account.tsx
  apps/passport/app/routes/authenticate/$clientId/index.tsx
  apps/passport/app/routes/authorize.tsx
  platform/starbase/data/state/kv/FIXTURES/local-acmecorp
  platform/starbase/src/jsonrpc/methods/getAppPublicProps.ts
  platform/starbase/src/jsonrpc/validators/app.ts
  platform/starbase/src/nodes/application.ts
Labels: enhancement

#2170 fix(passport): If name of email is the same for two types of email addresses they both look selected
  packages/design-system/src/atoms/email/EmailSelect.stories.tsx
  packages/design-system/src/atoms/email/EmailSelect.tsx
Labels: bug

#2172 docs(scopes): Fix Scopes Typo
  docs/reference/scopes.md
Labels: documentation
