Repository proofzero/rollupid, pull requests merged in 2023-07, with the labels that each got.

#2458 fix(console): darkmode broken in preview
  apps/console/app/routes/apps/$clientId/designer.beta.tsx
  apps/console/package.json
  yarn.lock
Labels: bug

#2457 feat(console): Billing and Invoicing - Invoice and payments integration
  apps/console/app/routes/__layout/gnillib/index.tsx
  apps/console/app/routes/__layout/gnillib/portal.tsx
  apps/console/app/routes/__layout/gnillib/webhook.tsx
  apps/console/app/routes/apps/$clientId/gnillib.tsx
  apps/console/app/services/billing/stripe.ts
  apps/console/bindings.d.ts
  apps/console/wrangler.toml
  packages/types/email.ts
  packages/types/index.ts
  platform/account/src/jsonrpc/methods/getEntitlements.ts
  platform/account/src/jsonrpc/router.ts
  platform/address/src/jsonrpc/methods/sendReconciliationNotificationMethod.ts
  platform/address/src/jsonrpc/router.ts
  platform/email/emailTemplate.ts
  platform/email/src/emailFunctions.ts
  platform/email/src/jsonrpc/methods/sendReconciliationNotification.ts
  platform/email/src/jsonrpc/router.ts
  platform/starbase/src/jsonrpc/methods/reconcileAppSubscriptions.ts
  platform/starbase/src/jsonrpc/methods/setAppPlan.ts
  platform/starbase/src/jsonrpc/router.ts
  platform/starbase/src/nodes/application.ts
Labels: enhancement

#2463 fix(posthog): wrap posthog init in try catch
  apps/console/app/root.tsx
  apps/passport/app/root.tsx
Labels: enhancement

#2464 fix(billing): reconciliation email subject
  platform/email/emailTemplate.ts
  platform/email/wrangler.toml
Labels: enhancement

#2461 feat(console): Groups and group user management
  apps/console/app/components/SiteMenu/index.tsx
  apps/console/app/routes/__layout/groups.tsx
  apps/console/app/routes/__layout/groups/$groupID/index.tsx
  apps/console/app/routes/__layout/groups/$groupID/invite.tsx
  apps/console/app/routes/__layout/groups/create.tsx
  apps/console/app/routes/__layout/groups/index.tsx
  apps/console/app/routes/apps/$clientId/designer.beta.tsx
  packages/design-system/src/atoms/breadcrumbs/Breadcrumbs.tsx
  packages/design-system/src/atoms/lists/List.tsx
  packages/design-system/src/atoms/lists/ListItem.tsx
  packages/design-system/src/helpers/get-provider-icons.ts
  packages/design-system/src/molecules/modal/Modal.tsx
  packages/platform-middleware/inputValidators.ts
  packages/types/graph.ts
  packages/urns/identity-group.ts
  platform/account/package.json
  platform/account/src/constants.ts
  platform/account/src/context.ts
  platform/account/src/index.ts
  platform/account/src/jsonrpc/methods/identity-groups/createIdentityGroup.ts
  platform/account/src/jsonrpc/methods/identity-groups/getIdentityGroupMemberInvitations.ts
  platform/account/src/jsonrpc/methods/identity-groups/inviteIdentityGroupMember.ts
  platform/account/src/jsonrpc/methods/identity-groups/listIdentityGroups.ts
  platform/account/src/jsonrpc/router.ts
  platform/account/src/nodes/identity-group.ts
  platform/account/src/nodes/index.ts
  platform/account/src/types.ts
  platform/account/wrangler.toml
  yarn.lock
Labels: enhancement

#2467 fix(account): export durable object classes
  platform/account/src/index.ts
Labels: bug

#2468 fix(account): introduce new durable object class again
  platform/account/wrangler.toml
Labels: bug

#2470 fix(various): Email AddressURN and Team Email
  apps/console/app/routes/apps/$clientId/team.tsx
  apps/passport/app/routes/connect/email/otp.ts
Labels: bug

#2479 fix(passport): Style Fixes
  packages/design-system/src/helpers/get-text-color.ts
Labels: enhancement

#2478 chore(groups): empty state and hide menu item
  apps/console/app/components/SiteMenu/index.tsx
  apps/console/app/routes/__layout/groups/index.tsx
Labels: enhancement

#2500 chore(console): Service Plan Page Improvement
  apps/console/app/routes/apps/$clientId/billing.tsx
Labels: enhancement

#2496 fix(console): Entitlements gauge not shown when none assigned
  apps/console/app/routes/__layout/billing/index.tsx
Labels: bug

#2526 fix(console): domain upgrade button
  apps/console/app/routes/apps/$clientId/domain.tsx
Labels: bug

#2528 fix(console): Screen side image gets downscaled
  apps/console/app/components/IconPicker/index.tsx
  apps/console/app/routes/apps/$clientId/designer.tsx
Labels: bug, enhancement

#2511 chore(console): Add Indicators to Sidebar Navigation
  apps/console/app/components/SiteMenu/index.tsx
Labels: enhancement

#2545 chore(billing): update plan feature colors
  apps/console/app/routes/__layout/billing/index.tsx
  apps/console/app/routes/__layout/billing/plans.ts
  apps/console/app/routes/apps/$clientId/billing.tsx
Labels: enhancement
