Repository proofzero/rollupid, pull requests merged in 2023-05, with the labels that each got.

#2212 chore(docs): remove extra colons in the bearer token syntax
  docs/reference/galaxy-api.md
Labels: documentation

#2224 fix(passport): Continue with button display missing name
  apps/passport/app/routes/authenticate/$clientId/account.tsx
  packages/design-system/src/molecules/auth-button/AuthButton.tsx
Labels: bug

#2220 fix(passport): Lazy load wagmi on login screen
  apps/passport/app/components/connect-button/ConnectButton.tsx
  apps/passport/app/components/connect-oauth-button/index.tsx
  apps/passport/app/routes/authenticate/$clientId/index.tsx
  packages/design-system/src/molecules/auth-button/AuthButton.tsx
Labels: bug

#2248 fix(passport): infinite loop in account select
  apps/console/app/root.tsx
  apps/console/remix.config.js
  apps/passport/app/root.tsx
  apps/passport/bindings.d.ts
  apps/profile/app/root.tsx
  packages/design-system/src/atoms/accounts/ConnectedAccountSelect.tsx
  packages/design-system/src/hooks/useTreeshakeHack.tsx
Labels: bug

#2273 fix(passport): fix redirect URL when the wallet account is already connected
  apps/passport/app/routes/connect/$address/sign.tsx
  apps/passport/app/utils/authenticate.server.ts
Labels: bug

#2292 fix(starbase): missing `await` operator
  platform/starbase/src/nodes/application.ts
Labels: bug

#2315 feat(console): Email OTP designer
  apps/console/app/components/IconPicker/index.tsx
  apps/console/app/entry.server.tsx
  apps/console/app/routes/apps/$clientId/designer.beta.tsx
  apps/passport/app/platform.server.ts
  apps/passport/app/routes/connect/email/otp.ts
  apps/profile/app/routes/account/profile.tsx
  packages/design-system/src/atoms/form/InputTextarea.tsx
  platform/address/src/jsonrpc/methods/generateEmailOTP.ts
  platform/email/emailOtpTemplate.ts
  platform/email/src/emailFunctions.ts
  platform/email/src/jsonrpc/methods/sendOTPEmail.ts
  platform/starbase/src/jsonrpc/methods/getEmailOTPTheme.ts
  platform/starbase/src/jsonrpc/methods/setEmailOTPTheme.ts
  platform/starbase/src/jsonrpc/router.ts
  platform/starbase/src/jsonrpc/validators/app.ts
  platform/starbase/src/nodes/application.ts
Labels: enhancement
