Repository proofzero/rollupid, pull requests merged in 2023-01, with the labels that each got.

#1302 feat(console): complete app profile
  apps/console/app/components/AppBox/index.tsx
  apps/console/app/components/Applications/ApplicationList.tsx
  apps/console/app/components/Applications/ApplicationListItem.tsx
  apps/console/app/components/Applications/Auth/ApplicationAuth.tsx
  apps/console/app/components/Applications/Dashboard/ApplicationDashboard.tsx
  apps/console/app/components/DeleteAppModal/DeleteAppModal.tsx
  apps/console/app/components/IconPicker/index.tsx
  apps/console/app/components/RotateCredsModal/RotateCredsModal.tsx
  apps/console/app/components/SiteHeader/index.tsx
  apps/console/app/components/SiteMenu/appSelect.tsx
  apps/console/app/components/SiteMenu/index.tsx
  apps/console/app/images/danger.svg
  apps/console/app/root.tsx
  apps/console/app/routes/api/image-upload-url.tsx
  apps/console/app/routes/apps/$clientId.tsx
  apps/console/app/routes/apps/$clientId/auth.tsx
  apps/console/app/routes/apps/$clientId/index.tsx
  apps/console/app/routes/apps/delete.tsx
  apps/console/app/routes/dashboard/index.tsx
  apps/console/app/utilities/galaxy.server.ts
  apps/console/app/utilities/platform.server.tsx
  apps/console/bindings.d.ts
  apps/console/wrangler.toml
  apps/graphql.config.js
  apps/profile/app/components/head-nav/index.tsx
  apps/profile/app/components/nft-collection/ModaledNft.tsx
  apps/profile/app/components/nft-collection/NftModal.tsx
  apps/profile/app/components/nft-collection/SelectableNft.tsx
  apps/profile/app/helpers/index.ts
  apps/profile/app/helpers/nfts.ts
  apps/profile/app/routes/$profile.tsx
  apps/profile/app/routes/account/settings/profile.tsx
  apps/profile/app/routes/nfts/gallery.tsx
  packages/design-system/src/atoms/buttons/common.tsx
  packages/design-system/src/atoms/form/InputToggle.tsx
  packages/platform-clients/package.json
  packages/platform-clients/starbase.ts
  packages/utils/gateway-from-ipfs.ts
  packages/utils/index.ts
  platform/account/src/jsonrpc/router.ts
  platform/starbase/src/error.ts
  platform/starbase/src/index.ts
  platform/starbase/src/nodes/application/index.ts
  platform/starbase/src/schema.ts
  platform/starbase/src/types.ts
  yarn.lock
Labels: enhancement

#1351 docs(3id): Fix Mobile Docs
  docs/3id/index.md
Labels: documentation

#1367 docs(galaxy): Fix Slugs and Add GQL References
  docs/3id/console/console.md
  docs/3id/faq/faq.md
  docs/3id/galaxy/galaxy.md
  docs/3id/galaxy/reference.md
  docs/3id/graph/graph.md
  docs/3id/guides/guides.md
  docs/3id/index.md
  docs/3id/passport/passport.md
  docs/3id/profile/profile.md
  docs/CONTENTS.md
Labels: documentation

#1373 chore: bump wrangler to 2.7.1
  .yarn/cache/@miniflare-cache-npm-2.10.0-82f4518616-29d1d97438.zip
  .yarn/cache/@miniflare-cli-parser-npm-2.10.0-8f3f2c60ae-60183bc594.zip
  .yarn/cache/@miniflare-core-npm-2.10.0-ab27b998af-ff096a1e5c.zip
  .yarn/cache/@miniflare-d1-npm-2.10.0-86f8d9d130-84df69e495.zip
  .yarn/cache/@miniflare-durable-objects-npm-2.10.0-66f63860a3-b6267de24d.zip
  .yarn/cache/@miniflare-html-rewriter-npm-2.10.0-04a2387089-35e925e35f.zip
  .yarn/cache/@miniflare-http-server-npm-2.10.0-5cd62e93a2-e2cb204542.zip
  .yarn/cache/@miniflare-kv-npm-2.10.0-a816068370-1e6b4719ec.zip
  .yarn/cache/@miniflare-queues-npm-2.10.0-3370e37f66-4a9496cb2b.zip
  .yarn/cache/@miniflare-r2-npm-2.10.0-a6f152d27e-69a52d614e.zip
  .yarn/cache/@miniflare-runner-vm-npm-2.10.0-db76cdb412-4c4ab84607.zip
  .yarn/cache/@miniflare-scheduler-npm-2.10.0-270d310914-fef3bdf490.zip
  .yarn/cache/@miniflare-shared-npm-2.10.0-bffa2dd2d0-ec610c597d.zip
  .yarn/cache/@miniflare-sites-npm-2.10.0-0fd4df42d1-f2de5fba0e.zip
  .yarn/cache/@miniflare-storage-file-npm-2.10.0-4036acca6d-f4e3496b47.zip
  .yarn/cache/@miniflare-storage-memory-npm-2.10.0-0e42048ee6-0319072930.zip
  .yarn/cache/@miniflare-watcher-npm-2.10.0-38035115b1-ee4c4f1e0c.zip
  .yarn/cache/@miniflare-web-sockets-npm-2.10.0-c692730c7e-1a03093921.zip
  .yarn/cache/miniflare-npm-2.10.0-b4257fb572-f5c6103d56.zip
  .yarn/cache/wrangler-npm-2.4.4-3fb65a1953-0548a4e791.zip
  .yarn/cache/wrangler-npm-2.7.1-e72aad6d1a-adbb0b3412.zip
  apps/console/package.json
  apps/passport/package.json
  apps/profile/package.json
  platform/access/package.json
  platform/account/package.json
  platform/address/package.json
  platform/edges/package.json
  platform/galaxy/package.json
  platform/object/package.json
  platform/ping/package.json
  platform/starbase/package.json
  services/images/package.json
  services/indexer/package.json
  services/webhooks/package.json
  yarn.lock
Labels: dependencies

#1336 feat(profile): Add GA for Profile
  apps/profile/.dev.vars.example
  apps/profile/app/root.tsx
  apps/profile/app/utils/gtags.client.ts
  apps/profile/wrangler.toml
Labels: enhancement

#1338 feat(passport): Add GA for Passport
  apps/passport/.dev.vars.example
  apps/passport/app/root.tsx
  apps/passport/app/utils/gtags.client.ts
  apps/passport/wrangler.toml
Labels: enhancement

#1337 feat(console): Add GA for Console
  apps/console/.dev.vars.example
  apps/console/app/root.tsx
  apps/console/app/utils/gtags.client.ts
  apps/console/wrangler.toml
Labels: enhancement

#1378 fix(console): Fix Tabification Typo
  apps/console/app/root.tsx
Labels: enhancement

#1391 chore(passport): replace dependency for `keccak256` function
  .yarn/cache/@ethersproject-networks-npm-5.7.0-7758ee537e-4f4d77e7c5.zip
  .yarn/cache/@ethersproject-providers-npm-5.7.0-19785b2114-a6f80cea83.zip
  .yarn/cache/@ethersproject-web-npm-5.7.0-8f8cc127f6-9d4ca82f8b.zip
  .yarn/cache/ethers-npm-5.7.0-3cae1237da-03b16c194e.zip
  apps/passport/app/routes/authenticate/google/callback.ts
  apps/passport/package.json
  yarn.lock
Labels: dependencies

#1395 feat(threeid): manage connected addresses
  apps/profile/app/components/addresses/AddressList.stories.tsx
  apps/profile/app/components/addresses/AddressList.tsx
  apps/profile/app/components/addresses/AddressListItem.stories.tsx
  apps/profile/app/components/addresses/AddressListItem.tsx
  apps/profile/app/routes/account/settings.tsx
  apps/profile/app/routes/account/settings/connections.tsx
  packages/design-system/src/atoms/lists/SortableList.stories.tsx
  packages/design-system/src/atoms/lists/SortableList.tsx
  packages/design-system/src/atoms/pills/IconPill.stories.tsx
  packages/design-system/src/atoms/pills/IconPill.tsx
  packages/design-system/src/atoms/pills/Pill.tsx
  packages/design-system/src/atoms/pills/PrimaryPill.stories.tsx
  packages/design-system/src/atoms/pills/PrimaryPill.tsx
  packages/galaxy-client/gql/address.graphql
  packages/galaxy-client/index.ts
  platform/account/src/jsonrpc/router.ts
  platform/galaxy/src/schema/resolvers/profile.ts
  platform/galaxy/src/schema/types/address.ts
Labels: enhancement

#1330 feat(access): create edges to link sessions
  packages/platform-middleware/edges.ts
  packages/platform-middleware/inputValidators.ts
  packages/platform-middleware/jwt.ts
  platform/access/curl/kb_authorize.json
  platform/access/curl/kb_exchangeToken.json
  platform/access/curl/kb_getSession.json
  platform/access/curl/kb_revokeSession.json
  platform/access/curl/kb_verifyAuthorization.json
  platform/access/package.json
  platform/access/src/constants.ts
  platform/access/src/context.ts
  platform/access/src/jsonrpc/methods/exchangeToken.ts
  platform/access/src/jsonrpc/methods/getSession.ts
  platform/access/src/jsonrpc/methods/revokeSession.ts
  platform/access/src/jsonrpc/middleware/setAccessNode.ts
  platform/access/src/jsonrpc/router.ts
  platform/access/src/nodes/access.ts
  platform/access/src/types.ts
  platform/access/wrangler.toml
  platform/account/curl/getAddresses.json
  platform/account/curl/hasAddresses.json
  platform/account/src/context.ts
  platform/account/src/jsonrpc/methods/getAddresses.ts
  platform/account/src/jsonrpc/methods/getSessions.ts
  platform/account/src/jsonrpc/methods/hasAddresses.ts
  platform/account/src/jsonrpc/router.ts
  platform/address/curl/kb_resolveAccount.json
  platform/address/curl/kb_setAccount.json
  platform/address/curl/kb_unsetAccount.json
  platform/address/src/jsonrpc/methods/setAccount.ts
  platform/address/src/jsonrpc/methods/unsetAccount.ts
  platform/edges/curl/kb_getEdges.json
  platform/edges/curl/kb_makeEdge.json
  platform/edges/curl/kb_rmEdge.json
  platform/edges/src/db/impl/remove.ts
  platform/ping/curl/kb_delayInit.json
  platform/ping/curl/kb_init.json
  platform/ping/curl/kb_ping.json
  platform/ping/curl/kb_pong.json
  platform/starbase/curl/kb_appAuthCheck.json
  platform/starbase/curl/kb_appCreate.json
  platform/starbase/curl/kb_appDelete.json
  platform/starbase/curl/kb_appList.json
  platform/starbase/curl/kb_appProfile.json
  platform/starbase/curl/kb_appPublish.json
  platform/starbase/curl/kb_appRotateSecret.json
  platform/starbase/curl/kb_appScopes.json
  platform/starbase/curl/kb_appUpdate.json
  platform/starbase/curl/kb_initPlatform.json
  platform/starbase/curl/rpc.discover.json
  platform/starbase/curl/unknown_method.json
  yarn.lock
Labels: enhancement

#1386 feat(address): initial `vault` account
  apps/passport/app/routes/authenticate/google/callback.ts
  apps/passport/app/routes/authorize/index.tsx
  platform/address/package.json
  platform/address/src/constants.ts
  platform/address/src/context.ts
  platform/address/src/jsonrpc/methods/initVault.ts
  platform/address/src/jsonrpc/methods/resolveAccount.ts
  platform/address/src/jsonrpc/methods/verifyNonce.ts
  platform/address/src/jsonrpc/middlewares/parse3RN.ts
  platform/address/src/jsonrpc/router.ts
  platform/address/src/jsonrpc/validators/oauth.ts
  platform/address/src/nodes/address.ts
  yarn.lock
Labels: enhancement

#1406 chore(ui): generic sortable list
  .yarn/cache/@esbuild-win32-x64-npm-0.16.3-92b8a6bfb7-8.zip
  apps/profile/app/components/addresses/AddressList.tsx
  apps/profile/app/routes/account/settings/links.tsx
  apps/profile/package.json
  package.json
  packages/design-system/src/atoms/lists/SortableList.stories.tsx
  packages/design-system/src/atoms/lists/SortableList.tsx
  packages/design-system/src/atoms/lists/SortableListItem.tsx
  yarn.lock
Labels: enhancement

#1416 docs(profile): Add Profile Walkthrough
  docs/3id/guides/app-setup.md
  docs/3id/guides/guides.md
  docs/3id/guides/profile-setup.md
  docs/3id/img/profile-walkthrough/account-nft-picker-ss.png
  docs/3id/img/profile-walkthrough/account-nft-ss.png
  docs/3id/img/profile-walkthrough/account-settings-links-add-ss.png
  docs/3id/img/profile-walkthrough/account-settings-links-done-ss.png
  docs/3id/img/profile-walkthrough/account-settings-links-ss.png
  docs/3id/img/profile-walkthrough/account-settings-profile-ss.png
  docs/3id/img/profile-walkthrough/account-ss.png
  docs/3id/img/profile-walkthrough/login-1-ss.png
  docs/3id/img/profile-walkthrough/login-2-ss.png
  docs/3id/img/profile-walkthrough/login-3-ss.png
  docs/3id/img/profile-walkthrough/login-4-ss.png
  docs/3id/img/profile-walkthrough/login-5-ss.png
  docs/3id/img/profile-walkthrough/passport-ss.png
  docs/3id/img/profile-walkthrough/profile-done-link-nft-ss.png
  docs/3id/img/profile-walkthrough/profile-done-ss.png
  docs/3id/img/profile-walkthrough/profile-ss.png
  docs/CONTENTS.md
Labels: documentation

#1352 feat(console): Display button to copy secrets on reveal
  apps/console/app/components/Applications/Auth/ApplicationAuth.stories.tsx
  apps/console/app/components/Applications/Auth/ApplicationAuth.tsx
  apps/console/app/components/Applications/Dashboard/ApplicationDashboard.tsx
  apps/console/package.json
  packages/design-system/src/atoms/copier/Copier.tsx
  packages/design-system/src/atoms/form/ReadOnlyInput.tsx
  yarn.lock
Labels: enhancement

#1428 chore(console): polishing
  apps/console/app/components/Applications/Auth/ApplicationAuth.tsx
  apps/console/app/components/IconPicker/index.tsx
  apps/console/app/components/SiteHeader/index.tsx
  apps/console/app/components/SiteHeader/profile-link.tsx
  apps/console/app/components/SiteHeader/sign-out-link.tsx
  apps/console/app/components/SiteMenu/appSelect.tsx
  apps/console/app/helpers/rotation.tsx
  apps/console/app/root.tsx
  apps/console/app/routes/api/image-upload-url.tsx
  apps/console/app/routes/apps/$clientId.tsx
  apps/console/app/routes/apps/$clientId/auth.tsx
  apps/console/app/routes/apps/$clientId/index.tsx
  apps/console/app/routes/dashboard/index.tsx
  apps/console/app/routes/signout.tsx
  apps/console/bindings.d.ts
  apps/console/wrangler.toml
  apps/passport/app/routes/authenticate/$address/token.tsx
  apps/profile/app/components/head-nav/index.tsx
  apps/profile/app/components/hean-nav-links/index.tsx
  apps/profile/app/root.tsx
  apps/profile/app/routes/account.tsx
  apps/profile/global.d.ts
  apps/profile/wrangler.toml
  packages/design-system/src/atoms/form/Input.tsx
  packages/design-system/src/atoms/form/MultiSelect.tsx
  platform/starbase/src/jsonrpc/validators/app.ts
  services/images/src/index.ts
Labels: enhancement, good-first-issue

#1471 fix(passport): typo in the URL
  apps/passport/app/components/connect-twitter-button/index.tsx
Labels: bug

#1411 feat(platform): Add Custom Analytics and Service Metadata
  packages/platform-clients/analytics.ts
  packages/platform-clients/index.ts
  packages/platform-middleware/analytics.ts
  packages/types/context.ts
  packages/types/index.ts
  platform/access/src/context.ts
  platform/access/src/types.ts
  platform/access/wrangler.toml
  platform/account/src/context.ts
  platform/account/src/types.ts
  platform/account/wrangler.toml
  platform/address/src/context.ts
  platform/address/src/jsonrpc/methods/resolveAccount.ts
  platform/address/src/jsonrpc/router.ts
  platform/address/src/types.ts
  platform/address/wrangler.toml
  platform/edges/src/context.ts
  platform/edges/src/types.ts
  platform/edges/wrangler.toml
  platform/galaxy/src/env.ts
  platform/galaxy/src/schema/resolvers/account.ts
  platform/galaxy/src/schema/resolvers/address.ts
  platform/galaxy/src/schema/resolvers/nfts.ts
  platform/galaxy/src/schema/resolvers/utils/index.ts
  platform/galaxy/wrangler.toml
  platform/object/src/context.ts
  platform/object/src/jsonrpc/router.ts
  platform/object/src/types.ts
  platform/object/wrangler.toml
  platform/starbase/src/jsonrpc/context.ts
  platform/starbase/src/types.ts
  platform/starbase/wrangler.toml
Labels: enhancement

#1472 feat(passport): AppleId
  .github/workflows/main-passport.yaml
  .github/workflows/next-passport.yaml
  .github/workflows/release-passport.yaml
  apps/passport/.dev.vars.example
  apps/passport/app/auth.server.ts
  apps/passport/app/components/authentication/Authentication.tsx
  apps/passport/app/components/connect-apple-button/index.tsx
  apps/passport/app/components/connect-apple-button/logo.svg
  apps/passport/app/routes/authenticate/apple/callback.ts
  apps/passport/app/routes/authenticate/apple/index.tsx
  apps/passport/app/routes/authorize.tsx
  apps/passport/app/utils/applestrategy.server.ts
  apps/passport/bindings.d.ts
  apps/passport/package.json
  apps/passport/wrangler.toml
  packages/types/address.ts
  platform/address/src/jsonrpc/methods/getAddressProfile.ts
  platform/address/src/jsonrpc/validators/oauth.ts
  platform/address/src/jsonrpc/validators/profile.ts
  platform/address/src/nodes/apple.ts
  platform/address/src/types.ts
  platform/address/src/utils.ts
  yarn.lock
Labels: enhancement

#1423 feat(profile): connected addresses
  .yarn/cache/@esbuild-win32-x64-npm-0.16.17-25af261435-8.zip
  apps/profile/app/components/addresses/AddressListItem.tsx
  apps/profile/app/helpers/profile.ts
  apps/profile/app/routes/account/settings.tsx
  apps/profile/app/routes/account/settings/connections.tsx
  apps/profile/app/routes/account/settings/connections/rename.tsx
  packages/design-system/src/atoms/lists/SortableListItem.tsx
  packages/galaxy-client/gql/address.graphql
  packages/galaxy-client/index.ts
  platform/address/src/jsonrpc/methods/initVault.ts
  platform/address/src/jsonrpc/methods/setAddressNickname.ts
  platform/address/src/jsonrpc/middlewares/setAddressNodeClient.ts
  platform/address/src/jsonrpc/router.ts
  platform/address/src/nodes/address.ts
  platform/address/src/nodes/crypto.ts
  platform/galaxy/src/schema/resolvers/account.ts
  platform/galaxy/src/schema/resolvers/address.ts
  platform/galaxy/src/schema/resolvers/utils/index.ts
  platform/galaxy/src/schema/types/address.ts
Labels: enhancement

#1490 fix(passport): authentication buttons
  .yarn/cache/@types-react-dom-npm-17.0.17-edb158f2b2-23caf98aa0.zip
  .yarn/cache/@types-react-npm-17.0.47-fa0afc8272-2e7fe0eb63.zip
  .yarn/cache/@types-react-npm-18.0.9-4dccadcd56-162364dad7.zip
  apps/passport/app/components/authentication/Authentication.tsx
  apps/passport/app/components/authentication/kubelt.svg
  apps/passport/app/components/connect-apple-button/index.tsx
  apps/passport/app/components/connect-button/ConnectButton.tsx
  apps/passport/app/components/connect-github-button/index.tsx
  apps/passport/app/components/connect-google-button/index.tsx
  apps/passport/app/components/connect-microsoft-button/index.tsx
  apps/passport/app/components/connect-oauth-button/apple.svg
  apps/passport/app/components/connect-oauth-button/github.svg
  apps/passport/app/components/connect-oauth-button/google.svg
  apps/passport/app/components/connect-oauth-button/index.tsx
  apps/passport/app/components/connect-oauth-button/microsoft.svg
  apps/passport/app/components/connect-oauth-button/twitter.svg
  apps/passport/app/components/connect-twitter-button/index.tsx
  apps/passport/app/entry.client.tsx
  apps/passport/package.json
  yarn.lock
Labels: enhancement
